### ISSUE TITLE
[ITensors] [BUG] StackOverflowError when using auto_fermion

### ISSUE THREAD

**Issue by nbaldelli** [ITensor/ITensors.jl#1002]
The REPL raises a StackOverflowError when initializing an MPS over fermionic sites, while having auto_fermion active. For example the code 

```julia
using ITensors

ITensors.enable_auto_fermion()

n = 10
s = siteinds("Electron", n)
psi = randomMPS(s, j -> isodd(j) ? "Up" : "Dn", linkdims=20)
```

returns the following error 

```julia
ERROR: StackOverflowError:
Stacktrace:
 [1] has_fermionic_subspaces(T::Tuple{Index{Int64}, Index{Int64}}) (repeats 2 times)
   @ ITensors ~/.julia/packages/ITensors/PisGD/src/physics/fermions.jl:46
```

This happen also when using the ```"Fermion"``` SiteType. The error is raised every time an MPS is manipulated after enabling auto_fermion, so for example 

```julia 

using ITensors

n = 10
s = siteinds("Fermion", n)
psi = randomMPS(s, j -> isodd(j) ? "1" : "0", linkdims=20)

ITensors.enable_auto_fermion()

inner(psi',psi)
```

returns the same StackOverflow error.

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8
```
 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
Status `~/.julia/environments/v1.8/Project.toml`
  [9136182c] ITensors v0.3.20
```

**Comment by mtfishman** [comment]
What happens when you enable QN conservation, i.e.:
```julia
s = siteinds("Fermion", n; conserve_qns=true)
```

In general, tracking the fermion sign is only well defined for QN conserving tensors since you need to track the fermion parity. However, it shouldn't break non-QN conserving code as you are seeing, so probably some definitions are missing for `has_fermionic_subspaces` for non-QN conserving indices.

**Comment by nbaldelli** [comment]
The code runs by adding the number conservation in the definition of the sites

**Comment by mtfishman** [comment]
Glad it works with QN conserving tensors.

Enabling the autofermion system with `ITensors.enable_auto_fermion()` shouldn't break non-QN conserving code, so let's keep this issue open. @emstoudenmire can you look into this?
