### ISSUE TITLE
[NDTensors] [BUG] permutedims!!() method doesn't use strided, does unnecessary broadcasting

### ISSUE THREAD

**Issue by amilsted** [ITensor/ITensors.jl#1004]
There is a method
```julia
function permutedims!!(R::DenseTensor, T::DenseTensor, perm::Tuple, f::Function=(r, t) -> t)
  RR = convert(promote_type(typeof(R), typeof(T)), R)
  RA = ReshapedArray(data(RR), dims(RR), ())
  TA = ReshapedArray(data(T), dims(T), ())
  if !is_trivial_permutation(perm)
    TB = permutedims(TA, perm)
    RA .= f.(RA, TB)
  else
    # TODO: specialize for specific functions
    RA .= f.(RA, TA)
  end
  return RR
end
```
that is sometimes called when permuting a tensor. It is not using `@strided` for `permutedims()` and does unnecessary work `RA .= f.(RA, TB)` in case `f` has its default value.

Also, it looks like it could be doing inplace `permutedims!()`, as the type of `RA` is in any case not dependent on the function `f` in the current implementation.

**Comment by mtfishman** [comment]
This is fixed in recent versions by just forwarding directly to `permutedims!`. Some of that logic will be reworked anyway going forward, for example the function should be handled through a `map` call, which we can fuse with the permutation using a `PermutedDimsArray` (or a `StridedView`) wrapper.
