### ISSUE TITLE
[ITensorGPU] [BUG] Time evolution on GPU and CPU don't give the same result

### ISSUE THREAD

**Issue by kbidzhiev** [ITensor/ITensors.jl#1013]
upd :  check issue[#1023](https://github.com/ITensor/ITensors.jl/issues/1023)

tdvp with a psi and a Hamiltonian on GPU doesn't give the same result as tdvp on CPU.
This bug doesn't depend on solver.

my MWE (minimal working example)
```julia
using ITensors, ITensorGPU, ITensorTDVP

let
    N = 10
    sites = siteinds("S=1/2", N)

    os = OpSum()
    for j = 1:(N-1)
        os += 0.5, "S+", j, "S-", j + 1
        os += 0.5, "S-", j, "S+", j + 1
    end
    H = MPO(ampo, sites)
    ψ = randomMPS(sites ; linkdims=1) #for linkdims>1 result is the same 

    cuH = cu(H)
    cuψ = cu(ψ)
    
    tau = 0.1
    ψ = tdvp(H, ψ, tau * 1.0im)  #CPU tdvp step
    cuψ = tdvp(cuH, cuψ, tau * 1.0im) #GPU tdvp step 
    
    enCPU = real(inner(ψ', H, ψ))
    enGPU = real(inner(cuψ', cuH, cuψ))
    @show enCPU - enGPU
end
```

**Comment by mtfishman** [comment]
Thanks for the report. Does it work with imaginary time evolution? I'm curious if it is specific to using complex numbers, which would indicate something like a missing complex conjugation somewhere.

**Comment by kbidzhiev** [comment]
solved in [1023](https://github.com/ITensor/ITensors.jl/issues/1023)
