### ISSUE TITLE
[NDTensors] [BUG] array(combiner * tensor) produces garbage

### ISSUE THREAD

**Issue by christopherdavidwhite** [ITensor/ITensors.jl#1034]
**Description of bug**

If I multiply a tensor by a combiner and then turn the result into a Julia array, I get garbage---it appears to be accessing uninitialized memory

**Minimal code demonstrating the bug or unexpected behavior**

```julia
using ITensors
using PkgVersion
@show VERSION
@show PkgVersion.Version(ITensors)

i = Index(2)
j = Index(3)
a = ITensor([1,2],i)

b = ITensor([1,1,1], j)

a |> array |> display
b |> array |> display
a*b |> array |> display

C = combiner(i,j)

C*a*b |> array |> display

```

**Expected output or behavior**
<details><summary>Expected output</summary>

```julia
VERSION = v"1.8.2"
PkgVersion.Version(ITensors) = v"0.3.21"
a |> array = [1.0, 2.0]
b |> array = [1.0, 1.0, 1.0]
a * b |> array = [1.0 1.0 1.0; 2.0 2.0 2.0]
C * a * b |> array = [1.0, 2.0, 1.0, 2.0, 1.0, 2.0]
```
</details>

**Actual output or behavior**

<details><summary>Actual output</summary>

```julia
VERSION = v"1.8.2"
PkgVersion.Version(ITensors) = v"0.3.21"
a |> array = [1.0, 2.0]
b |> array = [1.0, 1.0, 1.0]
a * b |> array = [1.0 1.0 1.0; 2.0 2.0 2.0]
C * a * b |> array = [1.0, 2.0, 6.93383344655886e-310, 6.93407979483234e-310, 6.9340145831688e-310, 6.93401455534304e-310]
```
</details>

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, tigerlake)
  Threads: 1 on 8 virtual cores
Environment:
  LD_LIBRARY_PATH = LD_LIBRARY_PATH:/home/christopher/software/lib


```
 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
  [9136182c] ITensors v0.3.21
```

**Comment by mtfishman** [comment]
It looks like the more fundamental issue is that it isn't throwing an error when the combiner is contracted with `a`:
```julia
julia> @show C * a;
C * a = ITensor ord=2
Dim 1: (dim=6|id=341|"CMB,Link")
Dim 2: (dim=3|id=140)
NDTensors.Dense{Float64, Vector{Float64}}
 6×3
   1.0   #undef  #undef
   2.0   #undef  #undef
 #undef  #undef  #undef
 #undef  #undef  #undef
 #undef  #undef  #undef
 #undef  #undef  #undef
```
Combiner contraction is only well defined for contracting over all of the indices of the combiner except the combined index.

**Comment by christopherdavidwhite** [comment]
Got it---parenthesizing fixes my example (and various bugs in my code). Thank you.

I'm not going to close; an error message on `C*a` would be very helpful.

**Comment by mtfishman** [comment]
Yes, definitely agree we should keep this issue open, we should be throwing an error for contractions like `C * a`.
