### ISSUE TITLE
Small change to AutoMPO syntax

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#107]
An alternative syntax we could use for AutoMPO is the following:

```julia
ampo = AutoMPO(sites)
for j=1:N-1
  ampo += ("Sz",j,"Sz",j+1)
  ampo += (0.5,"S+",j,"S-",j+1)
  ampo += (0.5,"S-",j,"S+",j+1)
end
```

as opposed to:

```julia
ampo = AutoMPO(sites)
for j=1:N-1
  add!(ampo,"Sz",j,"Sz",j+1)
  add!(ampo,0.5,"S+",j,"S-",j+1)
  add!(ampo,0.5,"S-",j,"S+",j+1)
end
```

This would get use very close to the C++ syntax. It should just require overloading `Base.:+(::AutoMPO,::Tuple)`.

@emstoudenmire, let me know what you think.

**Comment by mtfishman** [comment]
Unfortunately, using `+=` requires allocating a new `AutoMPO` each time a new term is added, but I doubt that would be a bottleneck anywhere. To avoid the allocation we can also overload broadcasting and use `.+=`.

**Comment by emstoudenmire** [comment]
That's a great idea. Yes too bad about the reallocation though. It won't be a bottleneck for typical lattice models, but we have also used AutoMPO in the past for quantum chemistry Hamiltonians with many thousands of terms! So it might still be acceptable there, but for that case one might prefer `.+=` or `add!` to avoid that overhead.
