### ISSUE TITLE
Bug in orthogonalize! when used with MPS with Dense{ComplexF64} storage

### ISSUE THREAD

**Issue by orialb** [ITensor/ITensors.jl#110]
Hi,

While working on my time evolution code I encountered a bug in `orthogonalize!` when the MPS has complex coefficients. Basically it seems that it is not bringing the MPS into a proper canonical form - after calling `orthogonalize!(psi,b)` ,  psi[b-1] is not left orthogonal and psi[b+1] is not right orthogonal.

Here is a minimal example:
```julia
using ITensors

basicRandomMPS(sites::SiteSet; kwargs...) = basicRandomMPS(Float64,sites; kwargs...)
function basicRandomMPS(T::Type, sites::SiteSet ;dim=4)
  M = MPS(sites)
  links = [Index(dim,"n=$(n-1),Link") for n=1:N+1]
  for n=1:N
    M[n] = randomITensor(T,links[n],sites[n],links[n+1])
  end
  M[1] *= delta(links[1])
  M[N] *= delta(links[N+1])
  M[1] /= sqrt(inner(M,M))
  return M
end

function MWE(T,b)
    sites = spinHalfSites(10)
    psi = basicRandomMPS(T,sites)
    orthogonalize!(psi,b)

    #check that psi[b-1] is left orthogonal
    L = psi[b-1]*prime(psi[b-1], b-1==1 ? "link" : commonindex(psi[b-1],psi[b]))
    l = linkindex(psi,b-1)
    err = norm(L-delta(l,l'))
    @assert  err < 1e-12 "$err < 1e-12"
end

MWE(Float64,3) # no problem

MWE(ComplexF64,3) # assertion fails
```

Note also that most of the tests in the `"MPS gauging and truncation"` test set (in `test_mps.jl`) fail if I use a random MPS with complex coefficients. 

I could try to dig into this, but I wonder whether it still occurs with the new `Tensor` design.

**Comment by orialb** [comment]
Sorry,I made a stupid mistake. I just realized my MWE is failing because I didn't take the conjugate of psi[b] while checking orthogonality, please ignore for the meantime (might be the reason for the bug somewhere in my time evolution code).

**Comment by emstoudenmire** [comment]
No problem. Thanks anyway!
