### ISSUE TITLE
Should there be an AbstractMPS type?

### ISSUE THREAD

**Issue by orialb** [ITensor/ITensors.jl#112]
Hi,

I think it could be useful to have an AbstractMPS type and have some of the MPS functions accept AbstractMPS.
The use case I have in mind is that it will allow users to define MPS wrappers that could represent for example a purification or a vectorized density matrix , for which different algorithms and operations are exactly the same as a regular MPS, but measurement of observables is done differently. Another use case could be for an iMPS. 

As a starting point it will be already useful to just define `AbstractMPS` and make `MPS <: AbstractMPS` without making any other changes to the code.

The question is what is the most minimal but still useful interface that defines an`AbstractMPS`.  I'll have to think about it a bit more, possibly after trying to actually implement some MPS wrapper.

**Comment by emstoudenmire** [comment]
Good question, but I think this sort of thing exposes an unresolved issue with generic programming in Julia and programming languages in general.

Should an MPO be considered an AbstractMPS? Or if not, should there be some concept like 1DTensorNetwork which they have in common? Or rather, is an MPO an AbstractOperator or is an MPS an AbstractWavefunction? 

As you can see, depending on context, types are sometimes one thing and sometimes other things. Yet inheritance is a concept that can only be deployed once, before all use cases have been properly explored.

For now we have taken the approach to generalizing certain methods which can apply to either MPS or MPO by restricting arguments to be ::Union{MPS,MPO}. A good thing about this approach is that it's "future proof" in the sense that we could add more things to the Union or just remove the type restriction altogether. Matt may have more to add here, and I think he's been finding more and more that it can be good to leave off types altogether in more high-level generic code for reasons like this.

So let's keep this in mind but for now I'm hesistant to define a supertype for MPS unless it enables us to do something we could not do before that.

**Comment by orialb** [comment]
thanks for the reply Miles. I see your point regarding how it can become a liability and cause unnecessary complications.  

> Matt may have more to add here, and I think he's been finding more and more that it can be good to leave off types altogether in more high-level generic code for reasons like this.

This sounds good (thinking about it  now, I recall reading somewhere that it's actually the recommended way to do thing in Julia instead of getting overexcited about type hierarchies like I was suggesting). There is still the question of which functions you consider high-level enough to not have the type restriction for MPS/MPO in them. For sure it would be nice in the long run to remove the type annotation from `dmrg` but I guess I should bring up a concrete use case first instead of opening vague issues :) .

**Comment by emstoudenmire** [comment]
Thanks for understanding, Ori. I think in an ideal programming language, the way to constrain function arguments would be based around which minimum properties the arguments must have for the code inside the function to work. So a function like `sort` would require `getindex` and `setindex!` and `length`, and this would be checked statically. The D programming language has gone quite a ways in realizing this idea & more - see talks by Alexandrescu on "Design by Introspection" or his most recent CppCon talk for more about this. But it's not a widely adopted language and also has its own drawbacks. I still like Julia more overall, especially for ITensor's use case and target audience.
