### ISSUE TITLE
[ITensors] [BUG] Precompile Fails (Can't find get_parameters)

### ISSUE THREAD

**Issue by ryanlevy** [ITensor/ITensors.jl#1177]
**Description of bug**

On Julia 1.9.2 the latest version if ITensors fails to precompile upon install

**Actual output or behavior**

<details><summary>Output of minimal runnable code</summary><p>

```julia
(@v1.9) pkg> precompile ITensors
Precompiling ITensors
  ✗ ITensors
  0 dependencies successfully precompiled in 4 seconds. 104 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

ITensors [9136182c-28ba-11e9-034c-db9fb085ebd5]

Failed to precompile ITensors [9136182c-28ba-11e9-034c-db9fb085ebd5] to "/mnt/home/rlevy/.julia/compiled/v1.9/ITensors/jl_bWnDaM".
WARNING: Method definition kwcall(Any, typeof(Base.sort), Tuple) in module Compat at /mnt/home/rlevy/.julia/packages/Compat/BJuif/src/Compat.jl:719 overwritten in module NDTensors at /mnt/home/rlevy/.julia/packages/NDTensors/28sKd/src/tupletools.jl:175.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition sort(Tuple) in module Compat at /mnt/home/rlevy/.julia/packages/Compat/BJuif/src/Compat.jl:719 overwritten in module NDTensors at /mnt/home/rlevy/.julia/packages/NDTensors/28sKd/src/tupletools.jl:175.
  ** incremental compilation may be fatally broken for this module **

ERROR: LoadError: UndefVarError: `get_parameters` not defined
Stacktrace:
 [1] include(mod::Module, _path::String)
   @ Base ./Base.jl:457
 [2] include(x::String)
   @ ITensors ~/.julia/packages/ITensors/wm7BG/src/ITensors.jl:51
 [3] top-level scope
   @ ~/.julia/packages/ITensors/wm7BG/src/ITensors.jl:108
 [4] include
   @ ./Base.jl:457 [inlined]
 [5] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2049
 [6] top-level scope
   @ stdin:3
in expression starting at /mnt/home/rlevy/.julia/packages/ITensors/wm7BG/src/imports.jl:132
in expression starting at /mnt/home/rlevy/.julia/packages/ITensors/wm7BG/src/ITensors.jl:1
in expression starting at stdin:3

```
</p></details>

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake-avx512)
  Threads: 1 on 24 virtual cores
Environment:
  LD_LIBRARY_PATH = /mnt/sw/nix/store/z5w5a7pr5cmdbds0pn9ajdgy0jg71sl6-gcc-11.3.0/lib64:/mnt/sw/nix/store/z5w5a7pr5cmdbds0pn9ajdgy0jg71sl6-gcc-11.3.0/lib:/mnt/sw/nix/store/0lj7r9gvs74j1rz053whdal23yizianw-python-3.10.8-view/lib:/mnt/sw/nix/store/1q1n408pwmzb9w00a8r7pvbip6m8ampl-intel-oneapi-mkl-2023.0.0/mkl/2023.0.0/lib/intel64:/mnt/sw/nix/store/1q1n408pwmzb9w00a8r7pvbip6m8ampl-intel-oneapi-mkl-2023.0.0/lib:/cm/shared/apps/slurm/current/lib64
  JULIA_IMAGE_THREADS = 1

```

**Comment by mtfishman** [comment]
Are you also using the latest version of NDTensors?

**Comment by kmp5VT** [comment]
I tried this 
```
bash> julia --project=monorepo
julia> using Pkg
julia> Pkg.add("ITensors")
julia> Pkg.precompile()
```
And I see no issue. Potentially there is a conflict with the other packages that you are using? Or you might need to explicitly add NDTensors. @mtfishman He doesn't specifically have NDTensors in his `Project.toml` he is just relying on ITensors to grab it and potentially its doing something wrong because you also have `ITensorGPU`?

**Comment by kmp5VT** [comment]
@ryanlevy This also tracks because when I do something like `Pkg.add("ITensorGPU")` with an empty project.toml, ITensorGPU grabs `ITensors@0.3.37` The most up to date version we found which doesn't break your build tree.

**Comment by ryanlevy** [comment]
Turns out something (maybe `ITensorGPU`?) was holding NDTensors back. It went from  NDTensors v0.1.51 ⇒ v0.2.9
 and seems to be working now, thanks!

**Comment by mtfishman** [comment]
Yeah, if you are using ITensorGPU that might be causing an issue forcing it to install an older version of NDTensors that isn't compatible with ITensors. I thought I fixed that so it installs consistent versions that work together but maybe there is still an issue with that.

If possible, just uninstall ITensorGPU.jl and try out the new package extension if you need to run ITensor on GPU (i.e. just load ITensors.jl and CUDA.jl and not ITensorGPU.jl)

**Comment by mtfishman** [comment]
My strategy for trying to fix that was to fix the compat version of ITensors in ITensorGPU: https://github.com/ITensor/ITensors.jl/blob/0a5a932eae91b5b8104ba6f19537003c6b17816f/ITensorGPU/Project.toml#L28-L29 but maybe that wasn't the right thing to do, since someone using an earlier version of ITensorGPU would have issues.
