### ISSUE TITLE
[ITensors] [BUG] DMRG for excited states return wrong state

### ISSUE THREAD

**Issue by muuusso** [ITensor/ITensors.jl#1187]
I'm running DMRG to find the first excited state of some Hamiltonian (composed only by $\sigma_z$ operators). I follow the example in the documentation and it seems to work fine, but the excited state (```psi1``` in the code below) returned by the DMRG function is actually the ground state. 

<details><summary>Minimal runnable code</summary><p>

```julia
psi0_init = randomMPS(sites, linkdims=10)
E0, psi0 = dmrg(H, psi0_init; nsweeps=nsweeps, maxdim=maxdim, cutoff=cutoff, noise=noise,
                    eigsolve_krylovdim=3, outputlevel=0, observer=observer)

psi1_init = randomMPS(sites, linkdims=10)
E1, psi1 = dmrg(H, [psi0], psi1_init; nsweeps=nsweeps, maxdim=maxdim, cutoff=cutoff, noise=noise,
                    eigsolve_krylovdim=4, outputlevel=0, observer=observer, weight=2)
println(E0)
println(E1)

println(inner(psi0', H, psi0))
println(inner(psi1', H, psi1))
```

</p></details>

<details><summary>Output of minimal runnable code</summary><p>

```julia
-64.99999999999872
-62.99999999999872
-64.99999999999874
-64.99999999999874
```

</p></details>

I checked that is the same state as the ground one by using the ```expect()``` function using ```"Z"``` as the local operator and they are the same state. 

If I had some $\sigma_x$ terms to the Hamiltonian the problem disappear and I get the expected behaviour.

CORRECTION

Even if  I add $\sigma_x$ terms the same thing happens, but it doesn't happen every time, just sometime.

**Comment by mtfishman** [comment]
Many of the variables are not defined (`sites`, `H`, `nsweeps`, etc.). Please share a self-contained code with everything defined, otherwise there's not much we can do to investigate the problem you are seeing.

Many times when this happens the `weight` isn't large enough, have you tried increasing it? Also, have you checked if the states are orthogonal to each other with `inner(psi0, psi1)`?

**Comment by muuusso** [comment]
You are right about the self-contained code, but for what I'm trying to say it isn't really relevant. If you inspect closely the output you can see that the the energy coming from the excited state dmrg function is -63 (```E1```), instead of -65 from the groundstate (```E0```), but when I try to compute the energies with the expectation values on ```H``` I get the same energy for both the states.

Here the self-contained code version (apart from ```H``` because the code is too long and not informative: it is an Hamiltonian composed by one body ($\sigma_i^z$) and two body operator ($\sigma_i^z \sigma^z_j$) for an Ising model).

```julia
N = 18
sites = siteinds("S=1/2", N)

const nsweeps::Int = 100
const maxdim::Int = 1000
const cutoff::Float64 = 1e-9
const noise::Vector{Float64} = [1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9]

const observer::DMRGObserver{Float64} = DMRGObserver(energy_tol=1e-6)

psi0_init = randomMPS(sites, linkdims=25)
    
E0, psi0 = dmrg(H, psi0_init; nsweeps, maxdim, cutoff, noise=noise,
                eigsolve_krylovdim=3, outputlevel=0, observer=observer)

psi1_init = randomMPS(sites, linkdims=25)

E1, psi1 = dmrg(H, [psi0], psi1_init; nsweeps, maxdim, cutoff, noise=noise,
                eigsolve_krylovdim=4, outputlevel=0, observer=observer, weight=2)

println(E0)
println(E1)

println(inner(psi0', H, psi0))
println(inner(psi1', H, psi1))
```

And yes I did check out if they are orthogonal by doing ```inner(psi0, psi1)``` and the result is -1: they are the same state.

**Comment by mtfishman** [comment]
The `dmrg` function reports the expectation value of `H + weight * |psi0><psi0|`, so that's why in this case where it seems to be finding the ground state, `E1` is `-63` instead of `-65`, i.e. it is `E0 + weight`.

**Comment by mtfishman** [comment]
From the perspective of the `dmrg` function, the operator it is finding the ground state of is `H + weight * |psi0><psi0|`, so it reports the expectation value of that operator. A practical reason is that internally, it is computing eigenvectors and eigenvalues of a projected version of `H + weight * |psi0><psi0|`, not `H`, so it would be extra work to compute the expectation value of `H` alone. However, you are free to compute the expectation value of `H` using an observer. Philosophically, we want to be pretty agnostic about what a user has in mind when they call `dmrg`, and also not specialize the functionality based on the operator that is passed except at a lower level where necessary for efficiency. Reporting the expectation value of `H` may make sense in the context of computing excited states, but may not make sense in other contexts where you happen to want the MPS eigenvector of an operator of the form `H + weight * |psi0><psi0|`.

Agreed we should add documentation for this, questions about this come up periodically.

**Comment by mtfishman** [comment]
Documentation added in https://github.com/ITensor/ITensors.jl/commit/c49da9e02f7c2465001f3a8446ad49faf23347d0.

**Comment by muuusso** [comment]
Thank you very much @mtfishman for your help. @titaschanda I tried that and it works, thanks.
