### ISSUE TITLE
Possible bug in MPOTerm, proposal for fix

### ISSUE THREAD

**Issue by MichaelSven** [ITensor/ITensors.jl#121]
Hi,

I noticed that when I run 
`
sites = spinHalfSites(4);
ampo = AutoMPO();
add!(ampo, "S+", 1, "S-", 2, "S+", 3, "S-", 4);
H = MPO(ampo, sites)
`
the error  "BoundsError: attempt to access 4-element Array{SiteOp,1} at index [5]" is thrown.
It seems to me like this should not happen and that it's due to lines 85-87 in autompo.jl
`
for n=1:2:length(ops);
    vop[2+n] = SiteOp(ops[n],ops[n+1]);
end
`
as n grows to length(ops) while length(vop) = length(ops) / 2.
A possible fix might be:
`
for n = 1:div(length(ops),2);
    vop[2+n] = SiteOp(ops[2*n-1],ops[2*n]);
end
`

I'll make a pull request with this fix and a four site Ising test that catches the issue. If I've misunderstood something and this is all expected behaviour then please ignore!

**Comment by emstoudenmire** [comment]
Great - thanks yes I should have written a better test that catches this!
