### ISSUE TITLE
[ITensors] [BUG] factorization in current ITensors version does not use eigen_perturbation

### ISSUE THREAD

**Issue by ntausend** [ITensor/ITensors.jl#1239]
**Description of bug**
Hey, I found that in the current version of ITensors the `factorization` method does not pass the `eigen_perturbation` keyword to the `factorize_eigen` function in line `785`.

**Minimal code demonstrating the bug or unexpected behavior**

No code needed.

**Version information**

 - Output from `versioninfo()`:
```julia
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 12 virtual cores
```
 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
ITensors v0.3.49
```

**Comment by mtfishman** [comment]
Thanks for the report. I refactored the keyword arguments in #1226, I guess it got lost in that rewrite. Will be a quick fix.
