### ISSUE TITLE
Slightly better `makeTagType` syntax

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#129]
Instead of using `Val{...}`, we can make our own simple `TagType{...}` struct:

```julia
struct TagType{N} end
```

Then instead of `makeTagType` we can just define a constructor for this type:

```julia
TagType(s) = TagType{Tag(s)}
# We can alternatively make it return an instance of the type,
# I am not sure which is better
TagType(s) = TagType{Tag(s)}()
```

This is just to avoid having to use `Val`, which might appear a bit mysterious.

**Comment by mtfishman** [comment]
An alternative is also to use a [non-stand string literal](https://docs.julialang.org/en/v1/manual/metaprogramming/#Non-Standard-String-Literals-1) here:

```julia
macro TagType_str(s)
  TagType{Tag(s)}
end

Electron = TagType"Electron"
```

Not too different from a function call, but maybe it tells users that something special is happening (that a type is being made).

**Comment by emstoudenmire** [comment]
Hi Matt, good suggestions. I think the first one we should do for sure, following the definition of `Val` exactly, but just using a different name than `Val` for the purpose of better error messages.

The second idea about string literals is neat, but I imagine may not get used very much. So I vote we just table that idea and come back to it if we start to see a good use case.
