### ISSUE TITLE
[ITensors] [BUG] Regression introduced to ITensors during refactor of NDTensors away from `kwargs...`

### ISSUE THREAD

**Issue by brian-dellabetta** [ITensor/ITensors.jl#1297]
**Description of bug**

A recent change to NDTensors introduced a regression into ITensors' `replacebond!` function for mps, see [here](https://github.com/ITensor/ITensors.jl/commit/70967cd1c1f0c9236450485446c2a10ad627bc07#diff-54a3468671071f1b6bdd9b5f64a92b16f4bbd68ce78561411a392f83fe14821dL530) for diff and responsible call to factorize just underneath.  Previously, users could set `min_blockdim`, `use_absolute_cutoff`, and `use_relative_cutoff` in the keyword args passed to `replacebond!`, and `kwargs...` would be passed correctly to factorize. This refactor away from kwargs is 100% welcomed as it makes the API more clear and readable, but it seems to have missed those fields, and possibly others or in other functions?

It also appears that factorize currently doesn't pass svd-related fields correctly into `factorize_svd` (see [here](https://github.com/ITensor/ITensors.jl/commit/70967cd1c1f0c9236450485446c2a10ad627bc07#diff-a9a827ce70a3014023e5fbe49a6271548c835958d56894de87d6843693d3746eL657), the svd fields don't seemed to be used anywhere in fact.

Happy to create a PR to add those fields if you agree, just let me know.

**Minimal code demonstrating the bug or unexpected behavior**

This succeeds in ITensors v0.3.48 & NDTensors v0.2.15
But fails in            ITensors v0.3.52 & NDTensors v0.2.23:

```julia
using ITensors
mps=randomMPS(Float64, [Index(2) for _ in 1:5])
replacebond!(mps, 2, mps[3]; which_decomp="svd", use_relative_cutoff=true, min_blockdim=1)
```

Error in v0.3.52:

```
ERROR: MethodError: no method matching replacebond!(::MPS, ::Int64, ::ITensor; which_decomp::String, use_relative_cutoff::Bool, min_blockdim::Int64)

Closest candidates are:
  replacebond!(::MPS, ::Int64, ::ITensor; normalize, swapsites, ortho, which_decomp, mindim, maxdim, cutoff, eigen_perturbation, svd_alg) got unsupported keyword arguments "use_relative_cutoff", "min_blockdim"
```

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 12 × Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
  Threads: 1 on 12 virtual cores
```

**Comment by mtfishman** [comment]
Thanks for the report, I'm not surprised some keyword arguments were lost in that PR since it was a pretty big undertaking. A PR would be welcome!

**Comment by brian-dellabetta** [comment]
#1300 submitted to resolve this issue, please lmk what you think!
