### ISSUE TITLE
[ITensors] [BUG] Custom Spin SiteType with arbitrary spin value

### ISSUE THREAD

**Issue by jubo97** [ITensor/ITensors.jl#1358]
**Description of bug**

Hi,
maybe this is not a bug but a pull request but anyways I want to calculate a system with a single spin (with different spin-values) and therefore I have to define my custom hilbert space as described [here](https://itensor.github.io/ITensors.jl/dev/examples/Physics.html#Make-a-Custom-Local-Hilbert-Space-/-Physical-Degree-of-Freedom).

If I use the code from the example this works fine.

If I now take the first step to extend this to arbitrary spin-values and insert the definitions for higher spin-matrices (as described [here](https://en.wikipedia.org/wiki/Spin_(physics)#Higher_spins)) this still works

**Minimal code demonstrating the bug or unexpected behavior**

<details><p>

```julia
hilbert_size = 4

ITensors.space(::SiteType"S=3/2") = hilbert_size
spin = 3/2

ITensors.op(::OpName"Sx",::SiteType"S=3/2") =
  1/2 .* [(Int(i == j+1) + Int(i+1 == j)) * sqrt((spin+1)*(i+j-1) - i*j)   for i in 1:hilbert_size, j in 1:hilbert_size]
    
N = 100
sites = ITensors.siteinds("S=3/2",N)
s = 1
test = op("Sx", sites[s])
```
</p></details>

The next extension I wanted to do was to change the spin-value globally by a variable "spin_value" as you can see in the following piece of code:

<details><p>

```julia
spin_value = 3/2
spin_string = string(spin_value)

hilbert_size = Int(2*spin_value + 1)

ITensors.space(::SiteType"S=$spin_string") = hilbert_size
    
ITensors.op(::OpName"Sx",::SiteType"S=$spin_string") = 
    1/2 .* [(Int(i == j+1) + Int(i+1 == j)) * sqrt((spin_value+1)*(i+j-1) - i*j)   for i in 1:hilbert_size, j in 1:hilbert_size]   
   
N = 100
sites = ITensors.siteinds("S=$spin_string",N)
s = 1
test = op("Sx", sites[s])
```
</p></details>

**Expected output or behavior**

I would expect to be able to just change the variable "spin_value" to whatever value I want it to have and my SiteType "S=spin_value" is assigned. 

**Actual output or behavior**

Somehow the overload of some funktions doesn't seem to behave as it should and I'm not able to build my "sites"-object with the "siteinds"-function.

<details><summary>Output of minimal runnable code</summary><p>

```julia
Overload of "space","siteind", or "siteinds" functions not found for Index tag: S=1.5

Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] siteind(st::SiteType{S=1.5}, n::Int64; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ITensors ~/.julia/packages/ITensors/WMeVS/src/physics/sitetype.jl:723
 [3] siteind(st::SiteType{S=1.5}, n::Int64)
   @ ITensors ~/.julia/packages/ITensors/WMeVS/src/physics/sitetype.jl:719
 [4] (::ITensors.var"#1127#1128"{Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SiteType{S=1.5}})(j::Int64)
   @ ITensors ./none:0
 [5] iterate
   @ ./generator.jl:47 [inlined]
 [6] collect(itr::Base.Generator{UnitRange{Int64}, ITensors.var"#1127#1128"{Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SiteType{S=1.5}}})
   @ Base ./array.jl:782
 [7] siteinds(tag::String, N::Int64; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ITensors ~/.julia/packages/ITensors/WMeVS/src/physics/sitetype.jl:769
 [8] siteinds(tag::String, N::Int64)
   @ ITensors ~/.julia/packages/ITensors/WMeVS/src/physics/sitetype.jl:761
 [9] top-level scope
   @ In[5]:24
```
</p></details>

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 20 × 12th Gen Intel(R) Core(TM) i7-12700
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, alderlake)
  Threads: 2 on 20 virtual cores
```
 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
Status `/amd/home/agfleischhauer/jbohm/.julia/environments/v1.9/Project.toml`
  [9136182c] ITensors v0.3.57
```

**Comment by mtfishman** [comment]
I'm not sure if this is the primary issue, but maybe you want to use `spin_value = "3/2"` instead of `spin_value = 3/2` so that it gets interpolated into `SiteType` as `3/2` instead of `1.5`.

**Comment by jubo97** [comment]
Actually I tried your first suggestion as well to directly enter the spin_string as a string but that didn't work out as well.

I'm confused you were not able to interpolate into SiteType. I just executed this piece of code:

```julia
spin_value = 5/2
spin_string = string(spin_value)
SiteType("x=$spin_string")
```

and the output has been as expected 

`SiteType{x=2.5}()`

or wouldn't I expect that to happen?

**Comment by mtfishman** [comment]
That is expected behavior.

Is there still an issue to address here?

**Comment by jubo97** [comment]
Maybe I was able to specify this problem a bit. I think it's a problem with the overloading of the functions. Maybe this is more a general julia thing than it's a problem of ITensors. Anyways here's what I found:

This piece of code here works just fine, defining the Index by hand (but with the "$spin_string" variable):

```julia
spin_value = 3/2
spin_string = string(spin_value)
hilbert_size = Int(2*spin_value) + 1
ITensors.space(::SiteType"S=$spin_string") = hilbert_size

s = Index(hilbert_size, "Site,S=$spin_string")

ITensors.op(::OpName"Sx",::SiteType"S=1.5") = 1/2 .* [(Int(i == j+1) + Int(i+1 == j)) * sqrt((spin_value+1)*(i+j-1) - i*j)   for i in 1:hilbert_size, j in 1:hilbert_size]
    
println(op("Sx", s))
```

If you execute this code it'll print out the Sx-matrix I'd expect for a spin 3/2.

But if I replace the `ITensors.op(::OpName"Sx",::SiteType"S=1.5")` with `ITensors.op(::OpName"Sx",::SiteType"S=$spin_string")` I get again the error that the Overload of "op" functions couldn't be found.

The function `siteind("S=$spin_string")` returns "nothing" no matter if I use "$spin_string" or "1.5".

**Comment by mtfishman** [comment]
One issue I see is that the line:
```julia
ITensors.space(::SiteType"S=$spin_string") = hilbert_size
```
will not interpolate `spin_string` into the type, for example try running this in your REPL:
```julia
julia> using ITensors

julia> spin_value = 3/2
1.5

julia> spin_string = string(spin_value)
"1.5"

julia> SiteType"S=$spin_string"
SiteType{S=$spin_string}

julia> SiteType("S=$spin_string")
SiteType{S=1.5}()
```
`SiteType"S=$spin_string"` and `SiteType("S=$spin_string")` act differently in terms of interpolation. You should be able to use:
```julia
ITensors.space(::typeof(SiteType("S=$spin_string"))) = hilbert_size
```
instead.

**Comment by jubo97** [comment]
Thanks for the help, this did work out fine for now.

Just for completeness here's the working example of the code:

```julia
spin_value = 3/2
spin_string = string(spin_value)
hilbert_size = Int(2*spin_value) + 1
#ITensors.space(::SiteType"S=$spin_string") = hilbert_size
ITensors.space(::typeof(SiteType("S=$spin_string"))) = hilbert_size

s = siteinds("S=$spin_string", 10)

ITensors.op(::OpName"Sx",::typeof(SiteType("S=$spin_string"))) = 1/2 .* [(Int(i == j+1) + Int(i+1 == j)) * sqrt((spin_value+1)*(i+j-1) - i*j)   for i in 1:hilbert_size, j in 1:hilbert_size]
    
println(op("Sx", s[4]))
```
