### ISSUE TITLE
[ITensors] [ENHANCEMENT]  Documentation about GPU support

### ISSUE THREAD

**Issue by iagoleal** [ITensor/ITensors.jl#1387]
Hello and, first of all, thank you for this amazing package!
  
**Is your feature request related to a problem? Please describe.**

Recently, I have been trying to adapt my ITensor code to take advantage of the CUDA GPU support but had a hard time figuring out how to do that. After spending a couple days searching all the docs, I finally stumbled upon this [discourse post](https://itensor.discourse.group/t/ann-initial-release-of-new-itensor-gpu-backends/1227) explaining the modern way to run the operations on the GPU.

That post solved my problem but I needed to do a lot of searching until I found it.

**Describe the solution you'd like**

 I think it may be easier for other users if there is a section about running ITensor.jl on the GPU on the official documentation site. This is quite a recent feature, so I understand that you may not have had the time to write the docs on it.

If you guys want, I can open a PR adding a section about GPU usage to the site. I think either the FAQ or the "Advanced Usage Guide" section would be a good fit. What do you think?

**Comment by mtfishman** [comment]
Agreed, we definitely need to document it better. We have been focusing on improving the internal code design, testing out performance, extending to other GPU backends and block sparse operations, adding accelerated contraction backends, etc. but I think the basics are in place now so it would make sense to add some simple documentation.

I think a new section of the "Advanced Usage Guide" called "Running on GPUs" would make sense.
