### ISSUE TITLE
[TensorAlgebra] [BUG] TensorAlgebra.blockedperm does not handle empty tuple correctly

### ISSUE THREAD

**Issue by ogauthe** [ITensor/ITensors.jl#1458]
```julia
using NDTensors.TensorAlgebra: TensorAlgebra
p1 = TensorAlgebra.blockedperm((),(2,1))
p2 = TensorAlgebra.blockedperm((),())
println(typeof(p1))
println(typeof(p2))
```
```
NDTensors.TensorAlgebra.BlockedPermutation{1, 2, Tuple{Tuple{Int64, Int64}}}
NDTensors.TensorAlgebra.BlockedPermutation{0, false, Tuple{}}
```
When both should be subtypes of `NDTensors.TensorAlgebra.BlockedPermutation{2}`

We previously discussed about removing this type and replacing it with a `Tuple{Tuple}` type. We need to decide whether to fix this or refactor the type.

**Comment by mtfishman** [comment]
Thanks for the report, should be easy to fix.

**Comment by mtfishman** [comment]
Seems like fixing this breaks some of the `contract` code since it is implicitly depending on this logic. I think some of the logic handling corner cases of fully contracted tensors is a bit misdesigned (related to #1428) so this will need to be fixed in conjunction with rewriting that logic.
