### ISSUE TITLE
Typo in `davidson` iterative solver

### ISSUE THREAD

**Issue by jtschneider** [ITensor/ITensors.jl#149]
https://github.com/ITensor/ITensors.jl/blob/724c1c56b757814682e505c2195fb048b6c0af37/src/iterativesolvers.jl#L72

There is a typo in the referenced line:
The `davidson` iterative solver would interpret keyword argument `maxiter` as both `maxiter` and `miniter`.

**Comment by jtschneider** [comment]
see also: pull request https://github.com/ITensor/ITensors.jl/pull/148
which includes a fix

**Comment by emstoudenmire** [comment]
Fixed by pull request #148
