### ISSUE TITLE
[ITensors] [BUG] Operator "S2" does not work for SiteType "S=1"

### ISSUE THREAD

**Issue by hankarls** [ITensor/ITensors.jl#1501]
**Description of bug**

It is not possible to create an `MPO()` with operator `S2` for the SiteType `S=1`. `S2` is listed as an available operator for SiteType `S=1` [here](https://itensor.github.io/ITensors.jl/stable/IncludedSiteTypes.html#%22S1%22-SiteType). It should be noted that the `S2`-operator works fine for SiteType `S=1/2`.

**Minimal code demonstrating the bug or unexpected behavior**

<details><summary>Minimal runnable code</summary><p>

```julia
using ITensors
sites = siteinds("S=1",10)
os = OpSum()
os += "S2", 3
mpo = MPO(os,sites)

```
</p></details>

**Expected output or behavior**

Expected an `mpo` corresponding to operator `S2` acting on site 3.

**Actual output or behavior**

<details><summary>Output of minimal runnable code</summary><p>

```julia
ERROR: ArgumentError: Overload of "op" or "op!" functions not found for operator name "S2" and Index tags: ("S=1,Site,n=3",).
```
</p></details>

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```

 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
Status `~/.julia/environments/v1.10/Project.toml`
⌅ [9136182c] ITensors v0.3.68
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated`
```

**Comment by emstoudenmire** [comment]
Yes, we should add this. I just made a PR #1502 to fix this. Thanks!
