### ISSUE TITLE
I  cant open   websit  doc

### ISSUE THREAD

**Issue by liu20001028** [ITensor/ITensors.jl#1525]
could you give you me a doc  about Itensor   !       l  can open it

**Comment by mtfishman** [comment]
Closing since this question was also posted to discourse: https://itensor.discourse.group/t/do-you-have-itensor-doc/1964. In general it is best to not repeat questions on both discourse and Github.

**Comment by mtfishman** [comment]
I'm able to access the website: https://www.itensor.org/ so I'm not sure what is going on but it is best to continue the discussion on discourse for now unless we identify a concrete issue to address.
