### ISSUE TITLE
Rename `array(::ITensor,::Index...)` -> `Array(::ITensor,::Index...)`

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#158]
This is to emphasize that a copy of the data is made, and distinguish it from `array(::ITensor)` which is a version that makes a view when possible as an optimization to avoid copying Dense ITensors.

Also add a version `Array{T}(::ITensor,::Index...)` to help with type inference, when the desired element type is known.

**Comment by emstoudenmire** [comment]
Yes, I think this is a good idea and your reply to Ori explained the situation and motivation well.
