### ISSUE TITLE
Question about how to mute tensor order warning

### ISSUE THREAD

**Issue by YiqingZhouKelly** [ITensor/ITensors.jl#159]
Hi,
Is there a way to mute the tensor order warning outside ITensors module? I am working with some tensors of high order (larger than the default `warnTensorOrder = 14` ) and want to stop the warnings. 

Thanks,
Yiqing

**Comment by orialb** [comment]
As far as I can see from the code it seems that at the moment there is no way to change this without changing the value of `ITensors.warnTensorOrder` (the warning seems to be printed with `println`, and not via`@warn`).

If you want to change it without actually changing ITensors.jl code, a quick hack that seems to work would be to do something like this:
`@eval ITensors warnTensorOrder=0`

Another option that seems to work for me:
```julia
using ITensors
import ITensors.warnTensorOrder

inds = fill(Index(2), 20)
A=randomITensor(inds...)

function f(A)
    warnTensorOrder=0
    return A*A
end
f(A)
```
 (i.e. it is possible to change the variable in the local scope of function f)
I'm not sure which way is preferable.

**Comment by YiqingZhouKelly** [comment]
Thanks! The first approach looks neat.

**Comment by orialb** [comment]
But I think a better approach would be to allow users to change this default (or at least silence the warning) somehow without using `@eval`. So maybe it's good to leave this issue open to get an opinion from Matt / Miles.

**Comment by YiqingZhouKelly** [comment]
Yes, I agree. Would be ideal if user can change this value without using these tricks.  Let me leave it open then :)

**Comment by emstoudenmire** [comment]
Thanks for pointing this out. We definitely need a good way to set this parameter to a custom value. So I just added a function `set_warnorder(ord)` you can call which will set the warn order to what you would like. Internally I moved this parameter into a dictionary so it can be modified at global scope.
