### ISSUE TITLE
Inaccurate svd results sometimes

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#160]
In the following code (as minimal as I could make it, because it depends on the tensor being SVD'd) I find that sometimes, like maybe every third or fourth time, the result of SVD'ing the tensor R gives low accuracy, meaning the relative error (truncation error) is in practice around 1E-8.

This problem goes away when a cutoff is specified, like `cutoff=1E-12`, which makes me suspect the bug is due to an interplay of how the truncate! function works and the default cutoff of exactly 0.0.

The important part is the last few lines below; the code at the top is necessary to prepare a tensor which has some nontrivial structure. When I input a totally random tensor the svd gives very accurate results every time. This makes me suspect the bug happens because R is approximately low-rank (which it is): it has one nearly-zero singular value.

```
using ITensors

let
  D = 8
  d = 2
  s1 = Index(D,"s1")
  s2 = Index(D,"s2")
  t1 = Index(d,"t1")
  t2 = Index(d,"t2")
  l1 = Index(d,"l1")

  MM = randomITensor(t1,s1,t2,s2)

  Q,R = qr(MM,(s1,s2))
  ii = commonindex(Q,R)
  u1 = Index(d,"u1")
  u2 = Index(d,"u2")
  split = ITensor(ii,u1,u2)
  for i=1:d,j=1:d
    split[ii(i+d*(j-1)),u1(i),u2(j)] = 1
  end
  R *= split

  #R1,S,R2 = svd(R,(u1,t1),cutoff=1E-12) #works well
  R1,S,R2 = svd(R,(u1,t1)) #sometimes leads to large differences
  R1 *= S
  @show norm(R)
  @show norm(R1*R2-R)
  @show norm(R1*R2-R)/norm(R) #should be < 1E-13 say
end
```

**Comment by mtfishman** [comment]
@emstoudenmire, this looks more like a problem with the svd function than the truncation. For example, when I run this until it fails to get a small error:
```julia
# ... (the rest of your code above forming R)
R1,S,R2 = svd(R,(u1,t1)) #sometimes leads to large differences
@show S
R1 *= S
@show norm(R)
@show norm(R1*R2-R)
@show norm(R1*R2-R)/norm(R) #should be < 1E-13 say
```
the output is:
```
S = ITensor ord=2 (4|id=707|Link,u) (4|id=707|Link,v) 
Diag{Float64,Array{Float64,1}}
4×4 Tensor{Float64,2,Diag{Float64,Array{Float64,1}},IndexSet{2}}:
 11.9778   0.0     0.0      0.0      
  0.0     10.9826  0.0      0.0      
  0.0      0.0     1.87994  0.0      
  0.0      0.0     0.0      9.3305e-8
norm(R) = 16.359050751143595
norm(R1 * R2 - R) = 9.330499138554323e-8
norm(R1 * R2 - R) / norm(R) = 5.703570017900987e-9
```
The error is exactly the final singular value, which should be zero. When I use `fastSVD=true` I don't see any problems with the last singular value (it is always zero and gets truncated).

**Comment by emstoudenmire** [comment]
Good find - thanks! Ok hmm so the custom recursive SVD function is messing up when there are very small singular values. This is not too surprising now with the benefit of hindsight, since it does the density matrix approach but then tries to correct this by recursively treating the smaller singular values (hence the name). 

It's unfortunate since I only put this in because the Julia SVD (which is what fastSVD=true does) was messing up in other cases that Yiqing was running into.

Maybe a short term fix could be to just make fastSVD default to true for now, then both identify a concrete case where fastSVD fails, as well as continue to improve our custom algorithm (maybe replacing it with a different algorithm if ultimately needed).
