### ISSUE TITLE
[ITensors] [BUG] Compilation using ``ITensors.compile()`` doesn't work; "No method is defined..."

### ISSUE THREAD

**Issue by jaredjeya** [ITensor/ITensors.jl#1605]
**Description of bug**

When running ITensors.compile(), as detailed [here](https://itensor.github.io/ITensors.jl/dev/AdvancedUsageGuide.html#Compiling-ITensors.jl), I get an error: the method doesn't seem to be found. The code in `compile.jl` seems to be missing: [see here](https://github.com/ITensor/ITensors.jl/blob/f55dbc407ac7c13144340b2e5b4e81e4274ad9cc/src/packagecompile/compile.jl#L53)

**Minimal code demonstrating the bug or unexpected behavior**

<details><summary>Minimal runnable code</summary><p>

```julia
using ITensors
ITensors.compile()
```
</p></details>

**Expected output or behavior**

ITensor compiles without issue.

**Actual output or behavior**

<details><summary>Output of minimal runnable code</summary><p>

```julia
julia> ITensors.compile()
ERROR: MethodError: no method matching compile(::NDTensors.BackendSelection.Algorithm{:PackageCompiler, @NamedTuple{}})
The function `compile` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  compile(; backend, kwargs...)
   @ ITensors ~/.julia/packages/ITensors/HwzqQ/src/packagecompile/compile.jl:39

Stacktrace:
 [1] compile(; backend::NDTensors.BackendSelection.Algorithm{:PackageCompiler, @NamedTuple{}}, kwargs::@Kwargs{})
   @ ITensors ~/.julia/packages/ITensors/HwzqQ/src/packagecompile/compile.jl:40
 [2] compile()
   @ ITensors ~/.julia/packages/ITensors/HwzqQ/src/packagecompile/compile.jl:39
 [3] top-level scope
   @ REPL[7]:1
```
</p></details>

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.11.2
Commit 5e9a32e7af2 (2024-12-01 20:02 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 48 × Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, broadwell)
Threads: 48 default, 0 interactive, 24 GC (on 48 virtual cores)
```
 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
Status `/storage/slow_raid5/SYSTEM/localhome/phyjj/[redacted]/Project.toml`
  [9136182c] ITensors v0.7.8
```

**Comment by mtfishman** [comment]
Please try loading `ITensorMPS.jl` before running `ITensors.compile()`, the compilation relies on running DMRG which is now in `ITensorMPS.jl`. See https://itensor.github.io/ITensors.jl/dev/#News.

**Comment by jaredjeya** [comment]
Thanks, I’ll try that.

Can you update the documentation to reflect that please, since it’s currently not clear? (A quick google for the error I had wasn’t helpful either)

**Comment by mtfishman** [comment]
Sure, will do.

**Comment by jaredjeya** [comment]
This actually still doesn't work for me. I'm doing exactly what you've put in the new docs, i.e.

```julia
using ITensors, ITensorMPS
ITensors.compile
```

but I get the same error.

**Comment by mtfishman** [comment]
Oops, sorry about that. I forgot you also have to install and load `PackageCompiler.jl` since the functionality was moved to a package extension so that we don't force everyone to install `PackageCompiler.jl` even if they don't want to use `ITensors.compile()`.

So this should work:
```julia
using ITensors, ITensorMPS
using PackageCompiler
ITensors.compile()
```
I'll clarify that in the docs.

**Comment by jaredjeya** [comment]
Thanks, seems to be working now!
