### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by orialb** [ITensor/ITensors.jl#183]
Hi,
Just a small comment on the installation instructions:
1. `LinearAlgbera, Printf, Random` are part of the standard library so they don't need to be installed. 
2. For installing ITensors (steps 3,4), is there a reason why you don't want users to install it via the package manager using `add  https://github.com/ITensor/ITensors.jl`?  (or alternatively they could `dev` a local copy if they plan to contribute). Isn't it considered better practice to use the package manager rather than manually adding a path to the LOAD_PATH ?

(actually if users use `add` or `dev` to install `ITensors` from the github/local repo I think they don't have to manually install any of the dependencies)

**Comment by orialb** [comment]
I guess it's not so important at the moment as it will anyway be changed once the package is registered, so I'll close it.

**Comment by emstoudenmire** [comment]
Hi Ori, I liked your approach better so I just updated the README. I had just forgotten you can do it that way.

I do hope that using `add` to install our pre-release version doesn't clash with the official version once we release that though. But in that case, we can just add instructions for people to help with removing the pre-release version files.

**Comment by orialb** [comment]
I did a small experiment with some other registered package. Seems like doing `add ITensors` once the package is registered will update the installation version to the latest tagged version even if it was added directly from Github before. 

```
(tmpenv) pkg> add https://github.com/JuliaStats/StatsBase.jl#fde3142
(tmpenv) pkg> st
    Status `~/tmp/tmpenv/Project.toml`
  [2913bbd2] StatsBase v0.31.0 #fde3142 (https://github.com/JuliaStats/StatsBase.jl)
(tmpenv) pkg> add StatsBase
(tmpenv) pkg> st
    Status `~/tmp/tmpenv/Project.toml`
  [2913bbd2] StatsBase v0.32.0
```

**Comment by emstoudenmire** [comment]
Great! Well done by the Julia team that made pkg. (Maybe that’s just Stefan Karpinski?)

Thanks for running this experiment Ori!
