### ISSUE TITLE
Roadmap says Combinatorics requires imagemagick, but I don't think that is true

### ISSUE THREAD

**Issue by cmcaine** [ITensor/ITensors.jl#20]
https://github.com/ITensor/ITensors.jl/blob/d5462fbf93e8fa332e4004d6a0b2c948b2c9acbc/ROADMAP#L8

Combinatorics.jl has one dependency, `Polynomials`, which has one dependency `RecipesBase`, which has no dependencies.

https://github.com/JuliaMath/Combinatorics.jl/blob/master/REQUIRE
https://github.com/JuliaMath/Polynomials.jl/blob/master/REQUIRE
https://github.com/JuliaPlots/RecipesBase.jl/blob/master/Project.toml

**Comment by emstoudenmire** [comment]
Good to know - I removed that from the roadmap
