### ISSUE TITLE
Default constructor for QNIndex

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#205]
For some developer-level code, it would be useful to be able to default-construct QNIndex objects. One place this is needed is for making a vector of default-initialized QNIndex before modifying some of the vector entries later. (A vector of the abstract supertype Index could be used instead, but being able to use the exact type should lead to better performance.)

**Comment by emstoudenmire** [comment]
Note that `Vector{QNIndex}(undef,N)` does currently work. And this is even better performing than an array of default-initialized QNIndex. But still it could be useful to have the default constructor.

**Comment by mtfishman** [comment]
Sounds like a good idea, we can just define:
```julia
QNIndex() = Index(IDType(0),Pair{QN,Int}[],Out,TagSet(("",0)))
```

**Comment by emstoudenmire** [comment]
Ok done on the AutoMPO branch I'm working on. Thanks!
