### ISSUE TITLE
`replaceindex!` and `replaceinds!` for QNIndex

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#218]
`replaceindex!` and `replaceinds!` need specialized versions for QN Indices to check the the QNs are the same and that the arrow directions are correct. Something like:
```julia
function replaceindex!(A::ITensor,i::QNIndex,j::QNIndex)
  space(i) != space(j) && error("Indices must have the same spaces to be replaced")
  pos = indexpositions(A,i)[1]
  newdir = dir(inds(A)[pos])
  inds(A)[pos] = setdir(j,newdir)
  return A
end
```
where `setdir(i::Index,dir::Arrow)` makes a copy of the Index with the direction set to the specified one.

**Comment by emstoudenmire** [comment]
Just a note for us: after implementing this, use in MPS replacesites! function. (On the AutoMPO branch, using a workaround approach for right now.)
