### ISSUE TITLE
blockview issue arising in combiner

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#231]
I am running some code which is a bit of an edge case, but a very important case. For background as to why it might be causing the bug below, it acts an MPO on a very simple product-state MPS (spinless fermion hopping Hamiltonian on a state with just a single fermion on one site).

At the end of doing naiveApplyMPO to act this MPO onto the MPS, the code calls `orthogonalize!` which puts the block-sparse tensor shown below into the `svd` function. The error then occurs at the beginning of `svd` where it makes the row and column indices with combiners.

The error is: "LoadError: Block must be structurally non-zero to get a view"

And the tensor going into the SVD is:

M[b] = ITensor ord=3

IndexSet{3,Index{Array{Pair{QN,Int64},1}}}
Dim 1: (dim=8|id=323|"CMB,Link") <Out>
 1: QN(("Nf",-1,-1)) => 2
 2: QN(("Nf",0,-1)) => 4
 3: QN(("Nf",1,-1)) => 2

Dim 2: (dim=2|id=904|"Fermion,Site,n=4") <Out>
 1: QN(("Nf",0,-1)) => 1
 2: QN(("Nf",1,-1)) => 1

Dim 3: (dim=5|id=235|"Link,u") <Out>
 1: QN(("Nf",1,-1)) => 2
 2: QN(("Nf",0,-1)) => 1
 3: QN(("Nf",1,-1)) => 2

BlockSparse{Float64,Array{Float64,1},3}
 8×2×5

Block: (2, 1, 2)
 [3:6, 1:1, 3:3]
[:, :, 1] =
 0.0
 1.0
 0.0
 0.0

Block: (1, 2, 2)
 [1:2, 2:2, 3:3]
[:, :, 1] =
 1.0
 0.0

Block: (2, 2, 3)
 [3:6, 2:2, 4:5]
[:, :, 1] =
 0.0
 0.0
 0.0
 0.0

[:, :, 2] =
 0.0
 0.0
 0.0
 0.0

Apparently there are some blocks which are numerically zero, but I'm unclear as to what is making the "pos" argument of `blockview` be `nothing`, which is what triggers the error condition in `blockview`. Thanks for the help with this!

**Comment by emstoudenmire** [comment]
Here's the entire code to reproduce (on the latest master branch including the new spinless fermion "Fermion" sites):
```
using ITensors

function hoppingMPO(sites;t1=1.0)::MPO
  H = MPO(length(sites))
  N = length(H)
  link = fill(QNIndex(),N+1)
  for n=1:N+1
    link[n] = Index(QN("Nf",0,-1)=>2,QN("Nf",+1,-1)=>1,QN("Nf",-1,-1)=>1;tags="Link,MPO,l=$(n-1)")
  end
  for n=1:N
    s = sites[n]
    ll = link[n]
    rl = link[n+1]
    H[n] = ITensor(dag(ll),dag(s),s',rl)
    H[n] += setelt(ll[1])*setelt(rl[1])*op(sites,"Id",n)
    H[n] += setelt(ll[2])*setelt(rl[2])*op(sites,"Id",n)
    H[n] += -t1*setelt(ll[2])*setelt(rl[3])*op(sites,"C",n)
    H[n] += t1*setelt(ll[2])*setelt(rl[4])*op(sites,"Cdag",n)

    H[n] += setelt(ll[3])*setelt(rl[1])*op(sites,"Cdag",n)
    H[n] += setelt(ll[4])*setelt(rl[1])*op(sites,"C",n)
  end
  LE = setelt(link[1][2])
  RE = setelt(dag(link[N+1])[1])
  H[1] *= LE
  H[N] *= RE
  return H
end

function fockState(sites,is...)::MPS
  state = fill("0",length(sites))
  for i in is
    state[i] = "1"
  end
  return productMPS(sites,state)
end

let
  N = 5

  sites = siteinds("Fermion",N,conserve_qns=true)

  psi5 = fockState(sites,5)

  H = hoppingMPO(sites)

  Hpsi5 = applyMPO(H,psi5,method="naive")

end
```

**Comment by mtfishman** [comment]
Thanks for all of the details, I'll take a look.
