### ISSUE TITLE
Function name changes

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#245]
Function names:
- `applyMPO -> applympo`
- `densityMatrixApplyMPO -> applympo_densitymatrix`
- `naiveApplyMPO -> applympo_naive`
- `multMPO -> multmpo`
- `orthoCenter -> orthocenter`
- `set_leftlim! -> setleftlim!`
- `set_rightlim! -> setrightlim!`
- `tensors -> itensors` or `store` (for getting the vector of ITensors of the MPS/MPO storage)
- Make `dot` an alias for `inner` (to reflect Julia's [new](https://github.com/JuliaLang/julia/pull/32739) three-argument dot syntax)

Function keyword arguments:
- `DensityMatrix -> densitymatrix` (in `applympo`)
- `absoluteCutoff -> use_absolute_cutoff` (in `truncate!`)
- `doRelCutoff -> use_relative_cutoff` (in `truncate!`)

**Comment by emstoudenmire** [comment]
Fixed by #255
