### ISSUE TITLE
Weird Error When Connecting Sites N and 2 in Hamiltonian for J1-J2 Model

### ISSUE THREAD

**Issue by sujay-kazi** [ITensor/ITensors.jl#252]
I attempted to run DMRG on the J1-J2 model (https://en.wikipedia.org/wiki/J1_J2_model). However, when I try to do so, a few of the terms in the AutoMPO give me problems, namely the terms where I connect site N to site 2.

Here is an example. Try the code below--it should run correctly. Then uncomment the lines labeled "offending term" (these are the ones where I connect site N to site 2), and now the code should generate an error.

```
using ITensors
J1 = 1 # interaction strength fornearest neighbors
J2 = 0.5 # interaction strength for next nearest neighbors
N = 100
# J1 = 1, J2 = 0.5, N even for Majumdar-Ghosh model

sites = siteinds("S=1/2",N) # Create N spin-1/2 indices
# Input operator terms which define
# a Hamiltonian matrix, and convert
# these terms to an MPO tensor network
ampo = AutoMPO()
for j=1:N-1
  add!(ampo,J1,"Sx",j,"Sx",j+1)
  add!(ampo,J1,"Sy",j,"Sy",j+1)
  add!(ampo,J1,"Sz",j,"Sz",j+1)
end
for j=1:N-2
  add!(ampo,J2,"Sx",j,"Sx",j+2)
  add!(ampo,J2,"Sy",j,"Sy",j+2)
  add!(ampo,J2,"Sz",j,"Sz",j+2)
end
add!(ampo,J1,"Sx",N,"Sx",1)
add!(ampo,J1,"Sy",N,"Sy",1)
add!(ampo,J1,"Sz",N,"Sz",1)
add!(ampo,J2,"Sx",N-1,"Sx",1)
add!(ampo,J2,"Sy",N-1,"Sy",1)
add!(ampo,J2,"Sz",N-1,"Sz",1)
# add!(ampo,J2,"Sx",N,"Sx",2) # offending term
# add!(ampo,J2,"Sy",N,"Sy",2) # offending term
# add!(ampo,J2,"Sz",N,"Sz",2) # offending term
H = MPO(ampo,sites)

# Create an initial random matrix product state
psi0 = randomMPS(sites)

# Plan to do 5 passes or 'sweeps' of DMRG,
# setting maximum MPS internal dimensions
# for each sweep and maximum truncation cutoff
# used when adapting internal dimensions:
sweeps = Sweeps(5)
maxdim!(sweeps, 10,20,100,100,200)
cutoff!(sweeps, 1E-10)
@show sweeps

# Run the DMRG algorithm, returning energy
# (dominant eigenvalue) and optimized MPS
energy, psi = dmrg(H,psi0, sweeps) 
println("Final energy = $energy")
```

Just so you know, when I attempted to run the code with the three "offending term" lines all uncommented, my stacktrace looked like this:

```
LoadError: BoundsError: attempt to access 6×9 Array{Float64,2} at index [4, 10]
Stacktrace:
 [1] setindex! at .\array.jl:784 [inlined]
 [2] toMatrix(::Array{MatElem{Float64},1}) at C:\Users\user\.julia\packages\ITensors\WcoED\src\physics\autompo.jl:233
 [3] #svdMPO#254(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(ITensors.svdMPO), ::AutoMPO, ::Array{Index{Int64},1}) at C:\Users\user\.julia\packages\ITensors\WcoED\src\physics\autompo.jl:592
 [4] #toMPO#270 at C:\Users\user\.julia\packages\ITensors\WcoED\src\physics\autompo.jl:539 [inlined]
 [5] toMPO at C:\Users\user\.julia\packages\ITensors\WcoED\src\physics\autompo.jl:697 [inlined]
 [6] #MPO#271 at C:\Users\user\.julia\packages\ITensors\WcoED\src\physics\autompo.jl:704 [inlined]
 [7] MPO(::AutoMPO, ::Array{Index{Int64},1}) at C:\Users\user\.julia\packages\ITensors\WcoED\src\physics\autompo.jl:704
 [8] top-level scope at D:\Sujay Google Drive\Julia Files\J1-J2 Model (including Majumdar-Ghosh Model)\J1_J2_model.jl:61 
in expression starting at D:\Sujay Google Drive\Julia Files\J1-J2 Model (including Majumdar-Ghosh Model)\J1_J2_model.jl:28
```

One thing I find interesting is that, when I uncomment just some of the terms, the error can look a little bit different:
If I uncomment just the x term, then it says "attempt to access 6×7 Array{Float64,2} at index [5, 8]."
If I uncomment just the y term, then it says "attempt to access 6×8 Array{Float64,2} at index [6, 9]."
If I uncomment just the x and y terms, then it says "attempt to access 6×8 Array{Float64,2} at index [6, 9]."
For the other possible combinations (i.e. all of those that contain the z term), the error looked the same as in my first error message shown above. I tried but failed to figure out what's going on here, but maybe this could be helpful.

I don't see any meaningful difference between the offending terms and all of the other terms. As such, I have no idea why the code is not working as intended. Any help on this would be greatly appreciated.

**Comment by emstoudenmire** [comment]
Thanks for reporting this. It is very new code, so I would not be surprised if there are some bugs of this type, though we have been testing it too ourselves of course. We will look into it and post more here after we figure it out.
