### ISSUE TITLE
DMRG sometimes initializes in ground state already?

### ISSUE THREAD

**Issue by sujay-kazi** [ITensor/ITensors.jl#263]
To illustrate my point, here is some code that works as intended. Here, I am putting an Sz operator on each site.

```
using ITensors
N = 100
sites = siteinds("S=1",N)
ampo = AutoMPO()
for j=1:N
    add!(ampo,1,"Sz",j)
end
H = MPO(ampo,sites)
psi0 = randomMPS(sites)
sweeps = Sweeps(5)
maxdim!(sweeps, 10,20,100,100,200)
cutoff!(sweeps, 1E-10)
energy, psi = dmrg(H, psi0, sweeps)
```

This ends up giving me the following output, which has the features of a successful DMRG. It starts at some energy that is not the ground state, since psi0 is chosen randomly, and then it decreases the energy at each iteration until it converges to the ground state energy quite nicely (we know this is the ground state energy because Sz has eigenvalues -1, 0, +1):

```
After sweep 1 energy=-92.377961145783 maxlinkdim=5 time=0.227
After sweep 2 energy=-99.073234602263 maxlinkdim=17 time=0.372
After sweep 3 energy=-99.958120883602 maxlinkdim=26 time=0.492
After sweep 4 energy=-99.999398466300 maxlinkdim=18 time=0.377
After sweep 5 energy=-99.999997208509 maxlinkdim=9 time=0.224
Final energy = -99.99999720850917
```

However, if I modify the code so that I have an (Sz)^2 operator at each site, as shown here:

```
using ITensors
N = 100
sites = siteinds("S=1",N)
ampo = AutoMPO()
for j=1:N
    add!(ampo,1,"Sz*Sz",j)
end
H = MPO(ampo,sites)
psi0 = randomMPS(sites)
sweeps = Sweeps(5)
maxdim!(sweeps, 10,20,100,100,200)
cutoff!(sweeps, 1E-10)
energy, psi = dmrg(H, psi0, sweeps)
```

I end up getting a result as shown below. Here, the energy that the DMRG converges to is the correct ground state energy, since (Sz)^2 has eigenvalues of 0, +1, +1. However, somehow the DMRG is always perfectly at the ground state energy by the first iteration, which really shouldn't be happening if psi0 is chosen randomly:

```
After sweep 1 energy=0.000000000000 maxlinkdim=1 time=0.131
After sweep 2 energy=0.000000000000 maxlinkdim=1 time=0.089
After sweep 3 energy=0.000000000000 maxlinkdim=1 time=0.100
After sweep 4 energy=0.000000000000 maxlinkdim=1 time=0.089
After sweep 5 energy=0.000000000000 maxlinkdim=1 time=0.106
Final energy = 6.52909510446715e-30
```

I decided to take it further by trying out (Sz)^3, (Sz)^4, etc. on each site to see what happens. Notice that all of the odd powers will have eigenvalues -1, 0, +1 (so the ground state energy will be -N), while all of the even powers will have eigenvalues 0, +1, +1 (so the ground state energy will be 0). Ultimately, the same results as above occurred in each of these cases. The DMRG worked as intended (started away from ground state energy, nicely converged to ground state energy) for all of the odd powers, while the DMRG had the same issue (already exactly at the ground state energy by the end of the first sweep) for all of the even powers.

I really have no idea why this might be happening. If I had to put out a guess, I would guess the possibility of trouble dealing with Hamiltonians that are not traceless or issues with multiplying multiple operators on the same site in a term added to an AutoMPO object. I say this just because because it does seem that these are features that people are less likely to use in their code, and the code has generally seemed to be more vulnerable in such situations. But again, I really don't know. Any help with this would be greatly appreciated.

**Comment by emstoudenmire** [comment]
Hi, thanks for looking over the code so carefully. It really is helpful. 

In this case, could you clarify what is the expected behavior, different from the current one, which you would like to see? It sounds like here the DMRG code is either working very well, or extremely well. So those both seem like good situations. 

I do understand why it’s a bit surprising that it already finds the perfect energy in one sweep. But for such a simple Hamiltonian, and given that one DMRG sweep corresponds to *two* optimization passes over each individual site, it doesn’t seem too implausible that DMRG could converge very fast for such an ultra-local Hamiltonian.

**Comment by sujay-kazi** [comment]
Yeah, my main thing is that it seems really surprising that the DMRG should converge that fast, so it seemed as though it may be an error. You are right that what I showed above does not *necessarily* indicate an error--maybe it really is converging that fast. It just seems hard to believe that there should be such a stark difference between the even power case and the odd power case. Maybe I can run some more checks and report back on this if I see anything more conclusive.

**Comment by emstoudenmire** [comment]
One nice thing to do is to modify the dmrg code (src/mps/dmrg.jl) to print the energy after every single optimization step. (Which is something we should add an option to do through a named argument, actually!) Then you may see that for the first few steps, even the first N steps, it's not perfectly converged but just converges very quickly.

**Comment by sujay-kazi** [comment]
That's a good suggestion. It turns out you were right. I added the following line to the DMRG file (src/mps/dmrg.jl) at the end of the loop beginning with "for (b,ha) in sweepnext(N)":

```
if !quiet
      @printf("After sweep %d entry %d energy=%.12f maxlinkdim=%d\n",
            sw, b, energy, maxlinkdim(psi))
end
```

For N = 10 and Sz on each site, I got the following (I didn't bother putting the 5th sweep):

```
After sweep 1 entry 1 energy=1.277893184205 maxlinkdim=3
After sweep 1 entry 2 energy=0.513809644628 maxlinkdim=3
After sweep 1 entry 3 energy=-0.337848217947 maxlinkdim=3
After sweep 1 entry 4 energy=-1.634022590628 maxlinkdim=3
After sweep 1 entry 5 energy=-2.708855309051 maxlinkdim=3
After sweep 1 entry 6 energy=-3.961188384194 maxlinkdim=3
After sweep 1 entry 7 energy=-5.059944577702 maxlinkdim=3
After sweep 1 entry 8 energy=-5.640846835818 maxlinkdim=3
After sweep 1 entry 9 energy=-6.377331300974 maxlinkdim=3
After sweep 1 entry 9 energy=-6.974156285966 maxlinkdim=3
After sweep 1 entry 8 energy=-7.401956361421 maxlinkdim=5
After sweep 1 entry 7 energy=-7.752711596085 maxlinkdim=5
After sweep 1 entry 6 energy=-8.015690593287 maxlinkdim=5
After sweep 1 entry 5 energy=-8.101190932192 maxlinkdim=5
After sweep 1 entry 4 energy=-8.189271925422 maxlinkdim=5
After sweep 1 entry 3 energy=-8.653256391596 maxlinkdim=5
After sweep 1 entry 2 energy=-8.976834160399 maxlinkdim=5
After sweep 1 entry 1 energy=-9.142259835447 maxlinkdim=5
After sweep 1 energy=-9.142259835447 maxlinkdim=5 time=0.093
After sweep 2 entry 1 energy=-9.217311968560 maxlinkdim=5
After sweep 2 entry 2 energy=-9.432640817587 maxlinkdim=5
After sweep 2 entry 3 energy=-9.622753707129 maxlinkdim=9
After sweep 2 entry 4 energy=-9.725908747638 maxlinkdim=10
After sweep 2 entry 5 energy=-9.794330367846 maxlinkdim=11
After sweep 2 entry 6 energy=-9.841841492199 maxlinkdim=11
After sweep 2 entry 7 energy=-9.864550661779 maxlinkdim=11
After sweep 2 entry 8 energy=-9.971653520474 maxlinkdim=11
After sweep 2 entry 9 energy=-9.986966074554 maxlinkdim=11
After sweep 2 entry 9 energy=-9.992161504538 maxlinkdim=11
After sweep 2 entry 8 energy=-9.994223591579 maxlinkdim=11
After sweep 2 entry 7 energy=-9.995778579503 maxlinkdim=11
After sweep 2 entry 6 energy=-9.996965894599 maxlinkdim=11
After sweep 2 entry 5 energy=-9.998094982595 maxlinkdim=10
After sweep 2 entry 4 energy=-9.999567627760 maxlinkdim=10
After sweep 2 entry 3 energy=-9.999806093599 maxlinkdim=10
After sweep 2 entry 2 energy=-9.999879144906 maxlinkdim=10
After sweep 2 entry 1 energy=-9.999887017138 maxlinkdim=10
After sweep 2 energy=-9.999887017138 maxlinkdim=10 time=0.110
After sweep 3 entry 1 energy=-9.999887121527 maxlinkdim=10
After sweep 3 entry 2 energy=-9.999911596711 maxlinkdim=10
After sweep 3 entry 3 energy=-9.999923126125 maxlinkdim=10
After sweep 3 entry 4 energy=-9.999925980215 maxlinkdim=10
After sweep 3 entry 5 energy=-9.999949218562 maxlinkdim=10
After sweep 3 entry 6 energy=-9.999980229542 maxlinkdim=10
After sweep 3 entry 7 energy=-9.999995169424 maxlinkdim=7
After sweep 3 entry 8 energy=-9.999998441488 maxlinkdim=7
After sweep 3 entry 9 energy=-9.999999628732 maxlinkdim=7
After sweep 3 entry 9 energy=-9.999999817627 maxlinkdim=7
After sweep 3 entry 8 energy=-9.999999908847 maxlinkdim=7
After sweep 3 entry 7 energy=-9.999999961201 maxlinkdim=7
After sweep 3 entry 6 energy=-9.999999973338 maxlinkdim=7
After sweep 3 entry 5 energy=-9.999999979730 maxlinkdim=5
After sweep 3 entry 4 energy=-9.999999984980 maxlinkdim=5
After sweep 3 entry 3 energy=-9.999999985692 maxlinkdim=4
After sweep 3 entry 2 energy=-9.999999985810 maxlinkdim=4
After sweep 3 entry 1 energy=-9.999999985946 maxlinkdim=4
After sweep 3 energy=-9.999999985946 maxlinkdim=4 time=0.129
After sweep 4 entry 1 energy=-9.999999985946 maxlinkdim=4
After sweep 4 entry 2 energy=-9.999999985951 maxlinkdim=4
After sweep 4 entry 3 energy=-9.999999985953 maxlinkdim=4
After sweep 4 entry 4 energy=-9.999999986118 maxlinkdim=4
After sweep 4 entry 5 energy=-9.999999986180 maxlinkdim=4
After sweep 4 entry 6 energy=-9.999999989859 maxlinkdim=4
After sweep 4 entry 7 energy=-9.999999992921 maxlinkdim=4
After sweep 4 entry 8 energy=-9.999999999954 maxlinkdim=3
After sweep 4 entry 9 energy=-9.999999999959 maxlinkdim=1
After sweep 4 entry 9 energy=-9.999999999959 maxlinkdim=1
After sweep 4 entry 8 energy=-9.999999999959 maxlinkdim=1
After sweep 4 entry 7 energy=-10.000000000000 maxlinkdim=1
After sweep 4 entry 6 energy=-10.000000000000 maxlinkdim=1
After sweep 4 entry 5 energy=-10.000000000000 maxlinkdim=1
After sweep 4 entry 4 energy=-10.000000000000 maxlinkdim=1
After sweep 4 entry 3 energy=-10.000000000000 maxlinkdim=1
After sweep 4 entry 2 energy=-10.000000000000 maxlinkdim=1
After sweep 4 entry 1 energy=-10.000000000000 maxlinkdim=1
After sweep 4 energy=-10.000000000000 maxlinkdim=1 time=0.121
```

For N = 10 and (Sz)^2 on each site, I got the following (I didn't bother putting all 5 sweeps):

```
After sweep 1 entry 1 energy=4.667102035544 maxlinkdim=1
After sweep 1 entry 2 energy=4.617831579094 maxlinkdim=1
After sweep 1 entry 3 energy=3.619511865241 maxlinkdim=1
After sweep 1 entry 4 energy=3.036181105721 maxlinkdim=1
After sweep 1 entry 5 energy=2.104728804075 maxlinkdim=1
After sweep 1 entry 6 energy=1.525769525585 maxlinkdim=1
After sweep 1 entry 7 energy=0.714244720865 maxlinkdim=1
After sweep 1 entry 8 energy=0.618309805736 maxlinkdim=1
After sweep 1 entry 9 energy=0.000000000000 maxlinkdim=1
After sweep 1 entry 9 energy=0.000000000000 maxlinkdim=1
After sweep 1 entry 8 energy=0.000000000000 maxlinkdim=1
After sweep 1 entry 7 energy=0.000000000000 maxlinkdim=1
After sweep 1 entry 6 energy=0.000000000000 maxlinkdim=1
After sweep 1 entry 5 energy=0.000000000000 maxlinkdim=1
After sweep 1 entry 4 energy=0.000000000000 maxlinkdim=1
After sweep 1 entry 3 energy=0.000000000000 maxlinkdim=1
After sweep 1 entry 2 energy=0.000000000000 maxlinkdim=1
After sweep 1 entry 1 energy=0.000000000000 maxlinkdim=1
After sweep 1 energy=0.000000000000 maxlinkdim=1 time=0.051
```

So indeed, the DMRG just converged fully within the first sweep. In hindsight, I guess this makes sense, because if there aren't any interactions between , then the first sweep (in fact, the first half of the first sweep) can essentially just optimize individually on each site and find the ground state.

In fact, now I'm in a bit of the opposite state of where I was before. Instead of wondering why even powers of Sz are causing the DMRG to converge so fast, I am now left wondering why odd powers of Sz are causing the DMRG to *not* converge just as fast. If there aren't any interactions between the particles, then why doesn't the first half of the first sweep achieve the ground state the same way as it did for the even powers of Sz? Anyway, the DMRG is still working well enough in those cases, so I'm not sure how much this is worth worrying about.

**Comment by emstoudenmire** [comment]
Thanks for looking into this so carefully! I'll open a separate issue about printing options for the `dmrg` function.
