### ISSUE TITLE
Option to print every step in DMRG

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#267]
We should add a keyword option to print the energy and bond dimension, etc., after each step of DMRG, not just after each sweep. (See #263 for one example where this is useful.)

It's worth checking if this is better done by supplying a default Observer through that system, or just with a keyword arg to the dmrg function directly. (Probably the latter to allow the printing to work orthogonally to the choice of observer.)

**Comment by mtfishman** [comment]
This also made me wonder if we should pick a different energy that gets printed by default. I guess the last energy of the sweep makes sense, but maybe we could print both the last energy and the middle energy?

**Comment by emstoudenmire** [comment]
Fixed by #309
