### ISSUE TITLE
Track performance with benchmarks

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#273]
This is a reminder to start collecting a set of benchmarks to track, possibly run with every pull request to check for performance regressions. We can look into the package [PkgBenchmark.jl](https://github.com/JuliaCI/PkgBenchmark.jl) to help with this.

**Comment by emstoudenmire** [comment]
Great. One thing I wonder about is whether we can ensure the benchmarks get run on a computer with similar hardware each time? Like perhaps with Github actions or Travis there is a way to ensure this? Something to look into.

Of course as a fallback we can also run the benchmarks ourselves occasionally on some reference computer of our own.

**Comment by mtfishman** [comment]
There are some benchmarks that are run automatically with Github Actions now.
