### ISSUE TITLE
docs Index.md and index.md colliding

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#275]
Unfortunately, on Mac OS file systems files in a Git repo (and perhaps more generally) which have the same name up to casing (upper vs lower case) collide with each other. Right now on the latest master branch, the files docs/src/Index.md and docs/src/index.md keep overwriting each other every time I reset to master. Is it possible for one of these to have a different name?

**Comment by emstoudenmire** [comment]
I did a temporary "fix" just now through the Github web interface (commit 6d30a8f), renaming docs/src/Index.md to docs/src/IndexObject.md (just a stand-in name for now). Without making this change, I actually couldn't switch the state of the repo on my Mac to other branches or commits, even after trying "git stash" or "git reset --hard" to reset the status.

I'll try to think of a more permanent fix we can do going forward!

**Comment by mtfishman** [comment]
It is fixed now (I renamed it to `IndexType.md`, and renamed other files to `IndexSetType.md`, etc. to make things consistent). I think there is no way to rename `index.md`, it is the file name that Documenter.jl expects.
