### ISSUE TITLE
Issues with test/mpo.jl

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#295]
There seem to be some issues with the mpo.jl unit test file, but I am having trouble nailing them down. There are at least two issues:

- [ ] when doing julia runtests.jl on my computer, all of the tests pass. However, when running only julia mpo.jl (or doing include("mpo.jl") in the REPL), I get an error which has to do with the "." function (centered-dot symbol, not period, presumably an operator overload for either inner or do) not being defined. I can't actually find where it is defined in the source code, so I'm a bit confused about how these tests are passing in the first place.
- [ ] some of the numerical tests involving the `mul` function are failing, but only on one of the Travis machines. Perhaps the test is too numerically stringent? See PR #293 for an example of this. (I actually ran the tests twice for this PR to check that it wasn't a fluke.)

**Comment by mtfishman** [comment]
That is referring to the symbol `\cdot`, which in Julia's LinearAlgebra is an alias for the `dot` function. We can fix this by exporting the `\cdot` unicode character from ITensors.jl
