### ISSUE TITLE
Restore ITensor Array constructor(s)

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#296]
The ITensor constructors taking an Array as the first argument were removed in some recent changes to the library. But Matt and I have agreed it would be good to have these back. This issue is a reminder to restore them. (Note that there are non-copying / view semantics functions `itensor(A,..)` currently.)

**Comment by mtfishman** [comment]
There is this version availabe: https://github.com/ITensor/ITensors.jl/blob/master/src/itensor.jl#L220

Maybe we should also have a version `ITensor(::Array)` that uses the internal index order for the memory layout?

**Comment by emstoudenmire** [comment]
Great. Ok glad this is back!
