### ISSUE TITLE
`replacebond!` interface

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#300]
`replacebond!` uses the keyword `dir` with options `"fromleft"` and `"fromright"`, while `factorize` uses the keyword `ortho` with options `"left"` and `"right"`. This forces `replacebond!` to use some keyword argument gymnastics: https://github.com/ITensor/ITensors.jl/blob/c2d1a17914a2fc426afbc9a723ef1a36d217325a/src/mps/mps.jl#L298

It seems like we could just have `replacebond!` use the same keywords as `factorize`, since the concept of these functions is quite similar.

**Comment by mtfishman** [comment]
Another argument for the change besides code simplicity: `dir` and `"fromleft"`/`"fromright"` are very DMRG-oriented terms, but `replacebond!` is a more general function.

**Comment by emstoudenmire** [comment]
Agreed. The names “left” and “right” sound just as good to me. So let’s do this change!

**Comment by emstoudenmire** [comment]
Let's be sure to change this inside of the `noiseterm` functions in projmpo.jl, projmposum.jl, projmpo_mps.jl too. (Otherwise the dmrg.jl tests likely won't pass.)
