### ISSUE TITLE
Calling scalar on QNITensor with no blocks gives error

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#307]
Currently, if a scalar (order-0) QNITensor `T` has no blocks (`nzblocks(T)==0`), then calling `scalar(T)` or `T[]` results in an error. Would it not be better to have `scalar(T)` return 0.0 for this case?

Example to reproduce:
```
s = siteinds("S=1/2",4;conserve_qns=true)
A = ITensor(s[1]'',dag(s[1]'))
B = ITensor(s[1]',dag(s[1]''))
A[1,1] = 1.0
B[2,2] = 1.0
R = A*B
@show scalar(R) #gives an error
```

**Comment by mtfishman** [comment]
Yeah that sounds right.
