### ISSUE TITLE
Final 0.1 release steps

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#329]
- [x] one round of "low-hanging fruit" optimizations e.g. exthubbard.jl DMRG example code
- [x] register NDTensors.jl package
- [x] Possible change to `eigen` interface (#331)
- [x] register ITensors.jl package
- [x] define v0.1.0 tag / create a Github release or similar
- [x] remove pre-install instructions from main page of docs
- [x] have Documenter create a stable version, linked to 0.1.0
- [x] update itensor.org Learn pages
- [x] update itensor.org front page links; C++ specific details; news
- [x] update [this](https://discourse.julialang.org/t/comparison-of-tensor-packages/11425) Julia Discourse thread

**Comment by emstoudenmire** [comment]
@mtfishman I was thinking we can keep adding to / editing this (at least I can edit, not sure if you can) to make sure we don't forget steps like those above as we get to 0.1

**Comment by mtfishman** [comment]
Sounds good. I'm able to edit it. I'll start adding ideas for possible breaking changes I come up with.
