### ISSUE TITLE
Seemingly no way to test old version of respository because cloning it leads to missing packages

### ISSUE THREAD

**Issue by sujay-kazi** [ITensor/ITensors.jl#339]
I decided to clone an old version of the ITensors repository (more specifically, pull request #287), to see how my code for DMRG on the spin-1/2 lattice formulation of the Schwinger model was working on an old version compared to a new version. However, when I did this, I got the following error:

```
ERROR: LoadError: ArgumentError: Package ITensors [9136182c-28ba-11e9-034c-db9fb085ebd5] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
 [1] _require(::Base.PkgId) at .\loading.jl:993
 [2] require(::Base.PkgId) at .\loading.jl:922
 [3] require(::Module, ::Symbol) at .\loading.jl:917
in expression starting at D:\Julia Files\Simple Examples\ITensors_test.jl:1
```

However, when I run "Pkg.instantiate," I see the following:

```
Updating registry at `C:\Users\user\.julia\registries\General`
Updating git-repo `https://github.com/JuliaRegistries/General.git`
Updating git-repo `https://github.com/ITensor/ITensors.jl`
```

This results in the latest version of the ITensors code being downloaded into the ITensors.jl folder, which means that there is no way, as far as I can tell, to test an old version of the code.

To be fair, I understand that this is pre-release and is thus going through a lot of changes, but I actually think that makes it all the more important to have this functionality. I say this in particular relation to issue #322 , where an error occurred in a newer version of the code that did not appear in an older version of the code. Is there some way I can test an old version of the code? Any help on this would be greatly appreciated.

**Comment by emstoudenmire** [comment]
Hi Sujay, I think this issue will get a lot easier after we officially register the package. 

Does the following approach work for you?
1. make a clean install of Julia, say on a different machine (without any packages installed yet, especially ITensors.jl)
2. use `git clone https://github.com/ITensor/ITensors.jl` to clone ITensors.jl into a folder somewhere
3. add this folder to your Julia LOAD_PATH `push!(LOAD_PATH,"/folder/name/where/ITensors.jl/is/cloned")`. You could put this line of code into your .julia/config/startup.jl

Then it may work better to switch the ITensors.jl folder to different versions. Not sure & maybe @mtfishman has a better suggestion. Or maybe this is already the approach you've tried?

**Comment by mtfishman** [comment]
@emstoudenmire, that was one way I was going to suggest.

The way I would switch between branches/commits that has worked for me is checking out the package in development mode. For example if I had installed ITensors.jl as follows:
```julia
julia> ]

(@v1.4) pkg> add https://github.com/ITensor/ITensors.jl
```
then I would use the development version of ITensors with the following command (in Pkg mode):
```julia
(@v1.4) pkg> dev ITensors
```
This creates a clone of `ITensors.jl` in the path `~/.julia/dev/ITensors` and when you type `using ITensors` it uses the version of ITensors.jl in that path. Then, you can enter the directory `~/.julia/dev/ITensors`, checkout whichever commit you are interested in, and that will be reflected in a new Julia session.

Perhaps you have already tried this. Please let us know what steps you tried/how you have ITensors.jl installed so we have a better idea of what is going on.

**Comment by orialb** [comment]
You can also tell the package manager to install a specific commit:
```julia
(test_commit) pkg> add https://github.com/ITensor/ITensors.jl#4ade960
 (test_commit) pkg> st
Status `~/tmp/test_commit/Project.toml`
  [9136182c] ITensors v0.1.0 #4ade960 (https://github.com/ITensor/ITensors.jl)
```
As far as I understand this should pin the version of ITensor to the specific commit.

But I personally find the approach described in Matt's comment above to be the most convenient if I frequently need to checkout different commits / branches .

**Comment by sujay-kazi** [comment]
Sorry for the late reply, but thank you all so much! I am very inexperienced with GitHub, so this was all very helpful.

Ultimately, the method suggested by @orialb worked very nicely, so I will stick with that for the time being. I also tried the method recommended by @mtfishman but ran into an issue--I have attached a picture of it to this reply.
![dev_ITensors_error](https://user-images.githubusercontent.com/45156122/81332626-3b9eb500-9058-11ea-900c-133f83a225e5.PNG)

**Comment by orialb** [comment]
>I also tried the method recommended by @mtfishman but ran into an issue

Since `ITensors` is not yet a registered package, it should probably be:
```julia
pkg> dev https://github.com/ITensor/ITensors.jl
```

Or if you already cloned `ITensors` to some local path 
```julia
pkg> dev /local/path/to/ITensors
```

I would recommend reading through the [documentation of the package manager](https://julialang.github.io/Pkg.jl/v1.4/) to learn more about package and environment management in Julia.

**Comment by mtfishman** [comment]
I think there are a few good suggestions for how to do this, so I'll close this issue. These types of things should become easier when we register the package (which I expect will be in a week or so).

**Comment by orialb** [comment]
> when we register the package (which I expect will be in a week or so).

Exciting!
