### ISSUE TITLE
Stable docs showing older README

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#376]
The Documenter docs linked by the stable/ url show an older index.md file which has the pre-release warning at the top. It would be good to update these (possibly tagging a new minor version) so that the stable docs are updated.

**Comment by mtfishman** [comment]
I will look into some last minute doc additions and possibly some new functions today, then will tag a new minor version.

**Comment by emstoudenmire** [comment]
Perfect, sounds good

**Comment by mtfishman** [comment]
It should be updated now that I tagged v0.1.1. It looks like the installation instructions still show the old method, instead of just `add ITensors`.

**Comment by emstoudenmire** [comment]
Yes, just noticed that too - I'll make a PR to remove that!
