### ISSUE TITLE
Fix random complex MPS

### ISSUE THREAD

**Issue by orialb** [ITensor/ITensors.jl#377]
Hi,
I noticed that `randomMPS(ComplexF64,sites)` (which used to give a random complex prodcut-state MPS) is no longer working because it calls `randomCircuitMPS` also when the bond dimension is 1, which is in turn only implemented for `Float64`. 

Should `randomMPS(complexF64,sites)` be implemented ? (also for the case of bond_dim > 1) 
Is the reason that it's not implemented currently because one has to implement `NDTensors.random_unitary` ?

**Comment by mtfishman** [comment]
Yes, I noticed that as well, Those should be implemented (as you say, with a non-existent `NDTensors.random_unitary` function).

**Comment by mtfishman** [comment]
`random_unitary` is in NDTensors now, so this should be easy to implement.
