### ISSUE TITLE
Improvements to TagSet and SmallString

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#381]
Here is an issue to track possible improvements to TagSet and Smallstring that we come across. For example some TagSet improvements:

 - [ ] Make an alias `ntags(::TagSet)` for `length(::TagSet)`, I get confused if `length` should output the length of the data structure or the number of tags. Possibly `length` should output the length of the total data structure.
 - [ ] Allow iterating a `TagSet` (over only non-trivial tags).
 - [ ] Make `TagSet <: AbstractString` (would help with generic code, that accepts String or TagSet).
 - [ ] Make the TagSet size a type parameter, and allow it to be adjusted with a global variable.

SmallString improvements:

 - [ ] Look through Julia `String` functions and implement some useful ones, for example `startswith`, `replace`, and `parse` to help do things like pick out the site number as an integer for a site Index of an MPS (i.e. the number `3` for an Index with TagSet `"Site,S=1/2,n=3"`)
 - [ ] Make `SmallString <: AbstractString` (would help with generic code, that accepts String or SmallString).
 - [ ] Define a string macro `@ss_str` for the notation `ss"mytag"`.
 - [ ] Make the SmallString size a type parameter, and allow it to be adjusted with a global variable.

We could also consider creating a separate package for `SmallString`, and maybe even for `TagSet`, though it may be too ITensor-specific.

**Comment by saolof** [comment]
Just one point of input: SmallString is currently mostly used for Tags with comparison and hashing being the most important operations. However, it is four times larger than a Julia Symbol and both more expensive to both hash and compare.

Adding methods to it would widen its interface, which can cause technical debt issues down the line, if for example you wanted to replace it with Symbol down the line.
