### ISSUE TITLE
exp for block sparse tensors

### ISSUE THREAD

**Issue by orialb** [ITensor/ITensors.jl#394]
Currently `exp` is only implemented for dense tensors on the `NDTensors` side, and it is not implemented for the case of ITensor with QN indices. 
Can I go on and implement `exp` for the QN case (I've already implemented the `NDTensors` part since it was very simple), or is it something you are working on/ want to wait with?

**Comment by mtfishman** [comment]
That would be great to have, please go ahead and contribute it (I'm not currently working on it, some of these were just oversights or were waiting for people to say they need it).

**Comment by orialb** [comment]
Implemented in https://github.com/ITensor/ITensors.jl/pull/402
