### ISSUE TITLE
Define `TagType(::AbstractString)`

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#400]
We could consider defining `TagType(s::AbstractString) = TagType{Tag(s)}()` as a nicer syntax for making an instance of a TagType, so instead of `TagType"S=1/2"()` you can write `TagType("S=1/2")`.

This is similar to how Julia defines `Val(x) = Val{x}()`.

**Comment by emstoudenmire** [comment]
Now supported for SiteType and similar types since version 0.1.13
