### ISSUE TITLE
avoid field with abstract type

### ISSUE THREAD

**Issue by Roger-luo** [ITensor/ITensors.jl#41]
https://github.com/ITensor/ITensors.jl/blob/7039c306b3a9a51954b1cd63b669a2ee451735a2/src/itensor.jl#L19

Ref: https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-fields-with-abstract-type-1

**Comment by emstoudenmire** [comment]
Thank you Roger, but this type is there intentionally so that ITensors can have diffferent storage types, even ones defined by users and not in the ITensors.jl code itself.

**Comment by Roger-luo** [comment]
I believe you can get the same behaviour with just a simple change, while avoiding the abstract field

```jl
mutable struct ITensor{S <: TensorStorage}
  inds::IndexSet
  store::S
  ITensor(is::IndexSet,st::T) where T = new(is,st)
end
```

**Comment by Roger-luo** [comment]
And I believe you don't even need an extra abstraction on storage in Julia, since you can directly dispatch things based on this type parameter.

**Comment by emstoudenmire** [comment]
That’s true, but please see the discussion in pull request #33

**Comment by Roger-luo** [comment]
I think the only difference is just instead of defining the inplace functions on your custom type, you can directly do it on the actual type itself since Julia is duck typed. This would make the structure more simple, it is not just about performance.

I'll join the discussion in the PR then.

**Comment by MasonProtter** [comment]
Now superseded by PR #48
