### ISSUE TITLE
Read MPOs/MPSs written out by C++ ITensor library

### ISSUE THREAD

**Issue by amartyabose** [ITensor/ITensors.jl#421]
Currently, ITensors.jl can read and write tensors to HDF5 files.  It would be nice to have a set of functions that ensure compatibility of data written out by the C++ ITensor library and ITensors.jl for subsequent "data analysis."

**Comment by emstoudenmire** [comment]
This is a timely issue - we got another request for this feature very recently, and it’s actually already in the works. I just need to complete it & was held up over some subtleties involving complex numbers. Unfortunately different HDF5 libraries write complex numbers to disk in incompatible ways. We may just pick an approach for now with those and add compatibility layers later, or else just only support real-valued tensors initially.

**Comment by amartyabose** [comment]
That's great.  Thanks!  I would have been willing to try my hand at it if you weren't already doing it.
