### ISSUE TITLE
MPO-MPS and MPO-MPO methods

### ISSUE THREAD

**Issue by kshyatt** [ITensor/ITensors.jl#45]
Would be nice to have `applyMPO`, `sum(::MPO, ::MPO0`, `nmultMPO`, and friends!

**Comment by emstoudenmire** [comment]
Yes! And they are all 1-indexed even in the C++ code. It’s almost as if we knew Julia was coming.

**Comment by mtfishman** [comment]
Yes, that was on my short to-do list. I just rewrote those fairly recently in C++ so it shouldn't be too hard.

**Comment by kshyatt** [comment]
I'm trying applyMPO now

**Comment by kshyatt** [comment]
We still need `errorMPOProd` if someone wants to claim it before I do

**Comment by emstoudenmire** [comment]
Looks like we have most of these now or are very close! Thanks Katie & others for working hard on this.
