### ISSUE TITLE
Simplify maxdim!, mindim!, etc. implementation with get

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#474]
In places like this:

https://github.com/ITensor/ITensors.jl/blob/2c4a59fe18d3f1f0d1e5e5b905c75c3a3060d6cf/src/mps/sweeps.jl#L135

we could simplify the implementation with the `get` function, for example:
```julia
for i in 1:nsweep(sw)
  sw.maxdim[i] = get(maxdims, i, maxdims[end])
end
```
The last value is a default if the index `i` is out of range.

We could even just not store all of the sweep values in the field `maxdim`, and define `getindex` through `get`, but that is probably not necessary.

**Comment by emstoudenmire** [comment]
Yes, that's a good idea because it makes the loop logic less fiddly. I didn't know that `get` allowed out-of-range indexes!
