### ISSUE TITLE
Add real(::ITensor) and complex(::ITensor)

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#504]
This can be implemented simply as `real(T::ITensor) = real.(T)`, etc.

**Comment by emstoudenmire** [comment]
I tried out doing `real.(T)` on a complex ITensor to see how easy this would be to add, and that approach kept the storage type as Dense{ComplexF64,...}, so the (zero) imaginary part is kept in the storage.

**Comment by mtfishman** [comment]
Must be something off about the broadcasting definitions for ITensors, since this works for NDTensors:
```julia
julia> i = Index(2)
(dim=2|id=349)

julia> A = randomITensor(ComplexF64, i)
ITensor ord=1 (dim=2|id=349)
NDTensors.Dense{ComplexF64, Vector{ComplexF64}}

julia> @show real.(A);
real.(A) = ITensor ord=1
Dim 1: (dim=2|id=349)
NDTensors.Dense{ComplexF64, Vector{ComplexF64}}
 2-element
 -0.16655805445944497 + 0.0im
   1.1369056057384508 + 0.0im

julia> using ITensors.NDTensors

julia> t = tensor(A)
Dim 1: (dim=2|id=349)
Dense{ComplexF64, Vector{ComplexF64}}
 2-element
 -0.16655805445944497 - 0.0005981723669549im
   1.1369056057384508 - 1.4307406994510203im

julia> real(t)
Dim 1: (dim=2|id=349)
Dense{Float64, Vector{Float64}}
 2-element
 -0.16655805445944497
  1.1369056057384508

julia> real.(t)
Dim 1: (dim=2|id=349)
Dense{Float64, Vector{Float64}}
 2-element
 -0.16655805445944497
  1.1369056057384508
```
For now we could just define `real(T::ITensor) = itensor(real(tensor(T)))`.

**Comment by mtfishman** [comment]
This would be a good use case for using macros to generate function definitions like:
```julia
for f in (:real, :imag)
    @eval ($f)(T::ITensor) = itensor($f(tensor(T)))
end
```
I'm sure there are more functions with this pattern so they could just be added to the list.

**Comment by emstoudenmire** [comment]
I have a PR submitted to NDTensors now which should make this easy to implement for ITensors. (I also have a small ITensors PR ready to go.) With the new NDTensors PR code, all that's needed to implement this issue is the following code:

```
Base.real(T::ITensor) = itensor(real(tensor(T)))

Base.imag(T::ITensor) = itensor(imag(tensor(T)))

Base.conj(T::ITensor) = itensor(conj(tensor(T)))
```

(I'm throwing in conj as another function we could offer.)
