### ISSUE TITLE
Advertise the `examples` directory better

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#521]
We need to advertise the `examples` directory in the documentation and on the website better (see e.g. http://www.itensor.org/support/2670/2d-hamiltonian-in-julia).

One thing we could do is link to https://github.com/ITensor/ITensors.jl/tree/master/examples and also give people instructions on how to access that from the command line. For example, with ITensors.jl installed, we can suggest an interactive way of running the examples:
```julia
julia> cd(joinpath(dirname(pathof(ITensors)), "..", "examples"))

julia> readdir()
6-element Array{String,1}:
 "basic_ops"
 "ctmrg"
 "dmrg"
 "gate_evolution"
 "src"
 "trg"

julia> cd("dmrg")

julia> readdir()
8-element Array{String,1}:
 "1d_heisenberg.jl"
 "1d_heisenberg_conserve_spin.jl"
 "1d_hubbard_extendend.jl"
 "1d_ising_with_observer.jl"
 "2d_heisenberg_conserve_spin.jl"
 "2d_hubbard_conserve_momentum.jl"
 "2d_hubbard_conserve_particles.jl"
 "input_files"

julia> include("1d_heisenberg.jl")
sweeps = Sweeps
1 cutoff=1.0E-11, maxdim=10, mindim=1, noise=0.0E+00
2 cutoff=1.0E-11, maxdim=20, mindim=1, noise=0.0E+00
3 cutoff=1.0E-11, maxdim=100, mindim=1, noise=0.0E+00
4 cutoff=1.0E-11, maxdim=100, mindim=1, noise=0.0E+00
5 cutoff=1.0E-11, maxdim=200, mindim=1, noise=0.0E+00

After sweep 1 energy=-138.797429981596 maxlinkdim=10 time=13.811
After sweep 2 energy=-138.937219110821 maxlinkdim=20 time=0.295
After sweep 3 energy=-138.940084426961 maxlinkdim=100 time=1.808
After sweep 4 energy=-138.940086088626 maxlinkdim=100 time=3.933
After sweep 5 energy=-138.940086113028 maxlinkdim=122 time=4.591
Final energy = -138.940086113028
```

**Comment by emstoudenmire** [comment]
Yes,  one thing about Julia having a package system is that people aren't as naturally led to look at the source code when using a library the first time. But agreed we can think of some easy fixes.

How about a specific page in the Documenter docs just about Examples (so that it shows up prominently in the table of contents)? It could feature a link to the examples folder and the instructions for running examples at a minimum, but could also list the examples one-by-one maybe just with short descriptions or even showing code if we want to get fancier with it.

**Comment by mtfishman** [comment]
Yeah, that's a good idea. Probably there is a way to show the code from the example files.

On master I've defined a function `ITensors.examples_dir()`:
```julia
examples_dir() = joinpath(dirname(pathof(@__MODULE__)), "..", "examples")
```
to make it easier to access that directory. So you can just do:
```julia
julia> cd(ITensors.examples_dir())

julia> cd("dmrg")

julia> include("1d_heisenberg.jl")
```

**Comment by mtfishman** [comment]
This has been implemented, see here: https://itensor.github.io/ITensors.jl/dev/#More-examples-1
