### ISSUE TITLE
Interface proposal for MPS/MPO Index related functions

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#527]
Here is an interface proposal for functions related to MPS/MPO. Currently there are some complicated function names, like:
```julia
unique_siteinds(H, psi)
prime_common_siteinds(H, psi)
sim_unique_siteinds(H, psi)
addtags_linkinds(psi)
```
To simplify these names, we could use the following type of notation:
```julia
siteinds(uniqueinds, H, psi)  # Return a vector with the site indices unique to H
prime(commoninds, siteinds, H, psi)  # Prime the site indices common between H and psi
sim(uniqueinds, siteinds, H, psi)  # Transform the indices unique to H to similar indices
addtags(linkinds, psi, "x") # Add the "x" tag to the link indices of psi
```
which will make use of dispatch, where in Julia each function has a unique type (i.e. the type of the function `f` is `typeof(f)`). The functions that are passed can be interpreted as "filters" that indicate that the function will act on the specified subset of indices. 

Another idea is to use functions like `only`, `all`, and `first` as flags when filtering indices:
```julia
siteinds(all, H) # Return a Vector of IndexSets of all site indices on MPO H
siteinds(first, H) # Return a Vector of the first Index found on MPO H
siteinds(only, H; plev = 0) # Return a Vector of the only Index found on MPO H with prime level of 0
```
as an alternative to having functions named `allsiteinds`, `firstsiteinds`, etc.

**Comment by emstoudenmire** [comment]
Glad to see this went in. A key step will be to make sure there is documentation for these cases, meaning examples of some of the things that can be plugged in.
