### ISSUE TITLE
Unfortunate bug when using `end` to index into ITensor

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#534]
Here is an unfortunate consequence of how Julia lowers the `end` syntax within `getindex`:
```julia
julia> i = Index(2, "i")
(dim=2|id=486|"i")

julia> j = Index(3, "j")
(dim=3|id=961|"j")

julia> A = randomITensor(i, j)
ITensor ord=2 (dim=2|id=486|"i") (dim=3|id=961|"j")
Dense{Float64,Array{Float64,1}}

julia> A[i => 2, j => 3]
-0.6219571237452334

julia> A[2, 3]
-0.6219571237452334

julia> A[end, end]
-0.6219571237452334

julia> A[i => end, j => end]
-0.6219571237452334

julia> A[j => end, i => end] # This is being interpreted by Julia as `A[j => 2, i => 3]`
-0.31234450698761396

julia> A[3, 2] # Here we need to add an inbounds check
-0.31234450698761396

julia> A[i => 3, j => 2] # Here we need to add an inbounds check
-0.31234450698761396

julia> lastindex(A, 1) # A[j => end, j => end] gets turned into A[j => lastindex(A, 1), i => lastindex(A, 2)], which causes problems
2

julia> lastindex(A, 2)
3
```
There are actually two bugs here. First is that because of the way Julia lowers `end` within `getindex` at a syntax level to `lastindex`, we may have to define `lastindex` in a different way to get the expression `A[j => end, i => end]` to work properly (since right now it doesn't take into account that we are indexing into the ITensor in a different order from the memory order of the ITensor storage). I think we could fix this by having `lastindex(A, n)` return a more sophisticated object than just the dimension as an integer, but that could have repercussions in other places.

The other bug here is that we are not doing bounds checking when indexing into ITensors (`A[3, 2]` should be throwing an error). The fix would be to put [bounds checking](https://docs.julialang.org/en/v1/devdocs/boundscheck/#Bounds-checking) in the correct locations in either ITensors.jl or NDTensors.jl.

**Comment by mtfishman** [comment]
Note that bounds checking for ITensors was added in #535. So in the latest version of ITensors.jl, the last 3 indexing examples will throw errors:
```julia
julia> A[j => end, i => end]
ERROR: BoundsError: [...]

julia> A[3, 2]
ERROR: BoundsError: [...]

julia> A[i => 3, j => 2]
ERROR: BoundsError: [...]
```

**Comment by emstoudenmire** [comment]
Just wanted to follow up on this to ask: why should `A[j=>end, i=>end]` now throw an error? Should not this be equivalent to `A[j=>3,i=>2]` where I've replaced `end` by the ending value of each Index? Or did you decide to just disallow the use of `end` in these calls? (Which I'm ok with doing if it just causes too many problems or can't be made to work correctly, but otherwise could be nice to have.)

**Comment by mtfishman** [comment]
@emstoudenmire, this is completely fixed and works as you would expect, i.e. `A[j=>end, i=>end] == A[j=>3, i=>2]`.

It was a relatively easy fix. The standard definition is `lastindex(A::AbstractArray, n::Int) = size(A, n)` (for Julia arrays, and generally arrays where the indexing always matches the memory layout of the array). For ITensors, the key was just defining that `lastindex(A::ITensor, n::Int) = LastVal(n)`, and then handling `LastVal` correctly in `getindex` by translating it into the largest value that the correct index could accept.

**Comment by emstoudenmire** [comment]
@mtfishman I see, great! I was just confused, then, by the examples of cases that were erroring above, but now I see it's been fixed to work the way one would hope or expect. That's a nice way to get the `lastindex` function to work.
