### ISSUE TITLE
Should we define iterate for TagSet?

### ISSUE THREAD

**Issue by tomohiro-soejima** [ITensor/ITensors.jl#542]
Currently, things like `for tag in tags(ind)` errors, since `iterate(t::TagSet)` is not defined. `TagSet` behaves like an iterable in most respects (e.g. it has `length`, it has linear `getindex`) so it might make sense to define `iterate` for it. I can open a pull request, if this looks like a good idea.

**Comment by mtfishman** [comment]
That sounds reasonable, a pull request would be welcome.
