### ISSUE TITLE
MPO-MPO multiplication for chain length N=1,2 not working

### ISSUE THREAD

**Issue by lidiastocker** [ITensor/ITensors.jl#544]
From the source code, I deduce that `Base.:*(A::MPO,B::MPO)` is implemented for N>=3. No warning message of type `("Base.:*(A::MPO,B::MPO) : currently only for chain length N>=3 supported"))` is given.

**Comment by mtfishman** [comment]
Thanks for pointing that out. Ideally it should work for those cases, but it must have been overlooked.
