### ISSUE TITLE
Use Symbol instead of SmallString in OpName

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#550]
If we switch OpName to use a Symbol instead of a SmallString, we could use longer operator names.

**Comment by emstoudenmire** [comment]
That’s interesting. Definitely would be good to allow longer op names (tags are less of an issue, though the limit can still be annoying there too). 

One question is how much does this change get exposed to the user? Another is whether it makes the internal code more complicated or the overload code harder to read for a person etc? Anyway we can prototype it and see how clean we can keep the design. I guess symbols and strings are practically not that different to work with.

**Comment by mtfishman** [comment]
I don't think it should get exposed, since users should never be making `SmallString`s themselves (they are all constructed internally).
