### ISSUE TITLE
AutoMPO slower than expected

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#555]
@emstoudenmire, I noticed the following:
```julia
using ITensors

function main(; Nrange = 10:10:40, conserve_qns = false)
  for N in Nrange
    @show N
    s = siteinds("S=1/2", N; conserve_qns = conserve_qns)
    a = AutoMPO()
    for k in 1:N, l in 1:N, m in 1:N, n in 1:N
      a .+= "projDn", k, "projDn", l, "projDn", m, "projDn", n
    end
    H = @time MPO(a, s)
    @show maxlinkdim(H)
  end
end
```
without QNs gives:
```julia
julia> main(conserve_qns = false)
N = 10
  0.058152 seconds (514.91 k allocations: 27.996 MiB, 12.61% gc time)
maxlinkdim(H) = 5
N = 20
  1.242284 seconds (9.57 M allocations: 510.026 MiB, 8.47% gc time)
maxlinkdim(H) = 5
N = 30
 11.900999 seconds (57.06 M allocations: 3.098 GiB, 6.61% gc time)
maxlinkdim(H) = 5
N = 40
 89.716646 seconds (208.21 M allocations: 11.901 GiB, 2.42% gc time)
maxlinkdim(H) = 5
```
and with QNs gives:
```julia
julia> main(conserve_qns = true)
N = 10
  0.106473 seconds (1.31 M allocations: 101.238 MiB)
maxlinkdim(H) = 5
N = 20
  3.248654 seconds (28.52 M allocations: 2.265 GiB, 13.98% gc time)
maxlinkdim(H) = 5
N = 30
 25.917715 seconds (189.34 M allocations: 15.664 GiB, 12.07% gc time)
maxlinkdim(H) = 5
N = 40
160.408265 seconds (746.00 M allocations: 63.665 GiB, 7.42% gc time)
maxlinkdim(H) = 5
```
Notice that the bond dimension of this particular MPO remains small.

**Comment by emstoudenmire** [comment]
I see, but is it not having to process 40^4 = 2,560,000 terms in the N=40 examples? I believe just the processing time for so many terms could account for a lot of the time needed, even though it's true the bond dimension ends up being small.

Regardless of whether the current algorithm can be sped up for this case, I do have in mind a different algorithm that I'd like to try based on some of the sliced-basis work I did with Steve. The current algorithm compresses the MPO at each bond rather separately of whether previous bonds have been compressed, whereas the newer algorithm I have in mind would sort of "push" the previously compressed basis from the left to the right and take advantage of it to speed up the next step. It would be helpful precisely for cases like this with many, longer-ranged terms.

**Comment by mtfishman** [comment]
Agreed there are a lot of terms to process, but it still seemed like something that could be sped up. That sounds good to investigate algorithmic changes.

Perhaps there is also some improvements to processing each term. From profiling the non QN version, I see that a lot of time is spent in:
 - `has_fermion_string` (maybe 25%-30% of runtime), which is dominated by `SiteType` constructors.
 - `posInLink!` (maybe 50% of runtime), which is dominated by `OpTerm` comparisons.
 - The rest is sorting the AutoMPO terms and removing duplicates, as well as the SVD in the compression step.

Probably the `posInLink!` is pretty fundamental (but maybe we could try optimizing the comparison). The calls to `has_fermion_string` could possibly be sped up. Since `has_fermion_string` has to search through the tags for a "proper" `SiteType` over and over, I was wondering if we could have a processing step that first identifies the `SiteType` (maybe by checking that it returns a nontrivial value for a certain function call) and then uses that `SiteType` throughout the code.

**Comment by mtfishman** [comment]
Maybe an idea would be that fermionic types define a fallback `has_fermionic_string` like:
```julia
has_fermion_string(::OpName, ::SiteType"Electron") = false
```
Then, as a first pass of all of the sites in the lattice, we check if any of the tags on the site returns `false` for `has_fermion_string(OpName("Id"), SiteType(tag))` (as opposed to `nothing`), in which case we store a vector of those tags. Then, we can "shortcut" the `has_fermionic_string` logic for cases when there are no tags that could be fermionic, and additionally "shortcut" the logic for having to search through every tag over and over and just use the tag that was identified as being potentially fermionic.

**Comment by emstoudenmire** [comment]
That's good profiling data to have. I definitely didn't write those steps which pre-process the terms with the highest performance in mind, so potentially a lot more can be done there. One general idea that could be used for that part and for the backend part that starts making the MPO is to make a Dictionary which caches the local site operators, since generally there are only a small handful of operators that get made on each site.

About the `has_fermion_string` function specifically, I'm in the process of removing it altogether in favor of the new fermion system which I worked on a lot yesterday and plan to keep working on this week.

**Comment by emstoudenmire** [comment]
I agree if there are some short-term improvements, like the fallback one mentioned above let's definitely do those!

**Comment by mtfishman** [comment]
Oh great, yeah I was thinking that the fermionic part of the code would just be replaced anyway. Glad to hear there has been progress on that. I'll look into it, it creates a very slight burden on people writing fermionic site types but I think they have to know what they are doing to a certain extent anyway.
