### ISSUE TITLE
Scalar ITensor for QN or BlockSparse Case

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#564]
It is a useful code pattern to start a chain of contractions from a scalar ITensor constructed as `ITensor(1.0)`. One example is building 'environment' tensors such as part of an MPO projected into an MPS basis.

Currently it appears that contraction of the form `ITensor(1.0) * T` where T is a QNITensor is not supported. I think this would be a good special case to handle, and the code could be specialized to the case of one of the tensors having zero indices.

**Comment by mtfishman** [comment]
Definitely would be good to have, I've had that on the back of my mind to add. We could even just do this at a very high level in the contraction function, where we check if either ITensor has `order(T) == 0 && isone(T[])` and then do no operation (i.e. return the other ITensor).
