### ISSUE TITLE
Finish coverage testing for storage/contract.jl

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#57]
The only remaining non-covered part of contract.jl is related to not having tests where one requests the indices of the result (C) in a different order from the "natural" matrix-matrix one. (Either that or the coverage site is buggy which it seems to be for other files!)

**Comment by mtfishman** [comment]
Yes, so far there is no user-facing code that calls those sorts of functions (the only in-place contraction where the output `C` is preallocated is multiplying with a scalar, i.e. `mul!(C,a,A)`, which calls a specialized permutation function).

Katie pointed out in #44 that the logic for the contraction code where `C` is preallocated (what will be the function `mul!(C,A,B)` that doesn't exist yet) seems to have a bug in it, so we need to take a closer look at it.

**Comment by mtfishman** [comment]
I believe this is covered by tests of the new `mul!(::ITensor, ::ITensor, ::ITensor)` function.
