### ISSUE TITLE
Use `onehot` as alternative syntax for `setelt`

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#580]
I noticed that the terminology "one-hot encoding" used in the context of digital circuits and machine learning [1,2,3] is essentially the same as our `setelt` ITensor constructor. It may be nice to use `onehot` as an alternative syntax, since it may be more familiar to people coming from that background (and I've wanted to find an alternative name for it anyway).

[1] https://en.wikipedia.org/wiki/One-hot
[2] https://www.tensorflow.org/api_docs/python/tf/one_hot
[3] https://fluxml.ai/Flux.jl/stable/data/onehot/

**Comment by emstoudenmire** [comment]
I think it's a good idea, as long as both names remain available (which I think is what you are proposing).
