### ISSUE TITLE
Remove tensor order as type parameter for `ITensor{N}` and `IndexSet{N}`

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#584]
I have been thinking about this design a lot, and I think it was bad decision to put the ITensor order as a type parameter in the `ITensor`/`IndexSet` types (I made the decision, so I'll kindly put the blame on myself). The most ubiquitous operation performed with ITensors is contraction, and in the case of contraction the resulting order of the ITensor is not known ahead of time (i.e. for most operations we do it is purely runtime). This makes it so that the `ITensor` order is almost never inferable by the Julia compiler, and puts unnecessary strain on the Julia compiler (it is constantly trying to infer the ITensor order, but most of the time it can't so the order is determined at runtime anyway).

Additionally, the most intensive operations on `IndexSet` objects are set operations (like `uniqueinds` and `commoninds`) which are also size-dynamic operations. That would point towards `IndexSet` naturally having a storage type that is dynamically sized, such as a `Vector{Index}`. In fact, those operations are implemented in terms of forming a Vector of indices and then converting back to an IndexSet (https://github.com/ITensor/ITensors.jl/blob/master/src/indexset.jl#L587-L593), which is not type stable. This of course was the design in C++ ITensor, which looking back I think was the right move.

I think the change won't be too much to make (and I think it could make some code simpler, especially the IndexSet code). However, it will of course be breaking to any users that were relying on those type parameters. I don't expect that is too common, but if it was the case than fixing it will mostly be a matter of removing the type parameter where necessary.

There is a tension with NDTensors that the Tensors in NDTensors do have the order as a type parameter, and I still think that is the correct decision there. I think we should handle that by uniformly converting the IndexSet to a Tuple when a Tensor is constructed, which will also make some NDTensor code simpler since then we can always assume the inds storage is a Tuple (and not rely on some convoluted generic code that had to account for the `inds` possibly being an `IndexSet`.

**Comment by emstoudenmire** [comment]
This sounds like a good improvement. For one thing it won't put a strain on users or likely break any of their code (or would be simple to upgrade). A side benefit, which seems small though which I think will make a smoother user experience is that ITensors can be used directly in array comprehensions without having to pre-pend ITensor[...] such as in the context of making a set of ITensor ops for gate or time evolution etc. Another small benefit is making some internal code a little less complex to read probably. If it has a big impact on JIT compilation time, that would be the best benefit of all. 

Your idea about turning IndexSets into tuples on the ITensor level makes sense to me. While the idea of having NDTensors code be highly generic is conceptually neat (and I think something I had pushed for), from the perspective of what you suggest, it's not hard to just convert inputs (especially in a language like Julia) to what NDTensors expects, and then it makes the NDTensors code much simpler and easier to debug.
