### ISSUE TITLE
doc link is broken

### ISSUE THREAD

**Issue by Roger-luo** [ITensor/ITensors.jl#599]
Hi guys, I was looking for some docs/tutorials on building DMRG from scratch, but then I found the mini course link is broken on ITensor webside: http://itensor.org/docs.cgi?vers=cppv3&page=course

---

also, wondering if there are any DMRG from scratch type tutorial or course you guys wrote before?

thanks!

**Comment by emstoudenmire** [comment]
Hi Roger, thanks for letting us know. That's an old page that is no longer linked to from anywhere else on the site I'm aware of. Perhaps you came across it from a Google search? But at any rate I'll remove it so that no longer happens.

Would the "Getting Started with DMRG" tutorial on this page cover the information you want?
http://itensor.org/docs.cgi?vers=julia&page=getting_started

**Comment by emstoudenmire** [comment]
A more up-to-date introduction to the basic workings of DMRG, based on that original course material is here under the heading titled "Tensor Networks and Applications":
http://tensornetwork.org/reviews_resources.html

Also there is an article at the following link about how the DMRG algorithm works:
http://tensornetwork.org/mps/algorithms/dmrg/

**Comment by Roger-luo** [comment]
> Perhaps you came across it from a Google search? 

Yes.

> Would the "Getting Started with DMRG" tutorial on this page cover the information you want?

I was looking for something like what I wrote previously for AD and quantum circuit simulators - basically, something teaches one to write a simple DMRG from scratch but with the intuition of something more complex like ITensors

> A more up-to-date introduction to the basic workings of DMRG, based on that original course material is here under the heading titled "Tensor Networks and Applications":
http://tensornetwork.org/reviews_resources.html

Thanks! that partially covers what I want!

**Comment by emstoudenmire** [comment]
Thanks for that feedback. I'd say that if you walk through that tensornetwork.org article, and pair it side-by-side with the DMRG code in ITensors.jl, looking also at the code for the ProjMPO type, then these follow each other closely in the main steps. Here are some relevant links to the source code:

ITensor dmrg function:
https://github.com/ITensor/ITensors.jl/blob/cc8bd44086bba4e67bfabe2a8ee1db1d09fecce8/src/mps/dmrg.jl#L93

ProjMPO type and methods:
https://github.com/ITensor/ITensors.jl/blob/master/src/mps/projmpo.jl
