### ISSUE TITLE
ArgumentError occur when i run the 1d_ising_with_observer example code

### ISSUE THREAD

**Issue by alexhuangweijie** [ITensor/ITensors.jl#603]
here is the ouput

Running DMRG for TFIM with h=0.1
================================
ERROR: LoadError: ArgumentError: Overload of "op" or "op!" functions not found for operator name "X" and Index tags: "S=1/2,Site,n=1")

**Comment by mtfishman** [comment]
Hi, it runs fine for me locally. What version are you using? Could you trying updating to the latest version?

**Comment by alexhuangweijie** [comment]
ok,I think my ITensors.jl version is too old. I will try to update it first.  thx for your reply.

**Comment by alexhuangweijie** [comment]
I updated my ITensor and  used the ITensors.compile(). It can run fine on my computer now. Thanks for your help.

**Comment by alexhuangweijie** [comment]
Should i close this issue?

**Comment by emstoudenmire** [comment]
Thanks for letting us know and checking about this issue. Glad updating fixed it for you!
