### ISSUE TITLE
Allow setting complex element of real ITensor

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#629]
We could allow setting an element of a real-valued ITensor to a complex value, which would of course case the storage to be converted to a complex valued storage. 

This change would ease usability in many cases, such as this recent question/comment on the support forum: http://itensor.org/support/2925/playing-with-mps-itensors-indexing?show=2958#c2958

**Comment by mtfishman** [comment]
Closed by #641.
