### ISSUE TITLE
Allow summing over equal indices in single Tensor

### ISSUE THREAD

**Issue by scipham** [ITensor/ITensors.jl#632]
To my knowledge there is no basic way to contract equal indices in a single ITensor 
e.g. when having a primed + unprimed copy an index in one tensor $T^s_s'$  and when resetting the prime level of the primed version, the tensor should contract over the created equal, unprimed index s automatically. Alternatively, a summing function for single ITensor objects could be provided to do this manually either by summing over all equal indices of the ITensor or by providing input of an Index(Set) of indices to sum over.

**Comment by emstoudenmire** [comment]
Thanks for raising this issue, as we want to make sure this operation is available. One way you should be able to do it is by contracting with a “delta” (Kronecker delta) tensor like this: 
`T *= delta(s,s’)`

Delta tensors have a special storage type that lets us implement contractions with them using optimized routines as well. 

Please let us know if that does what you need, and we will improve the docs to make this easier to find.

**Comment by scipham** [comment]
@emstoudenmire I see, thanks. I then rightfully have overseen such an operation. Just to keep things complete, to my given context it would even boil down to `T *= delta(s)`, but  `T *= delta(s, s')` indeed spares a line. 

I suggest to add this to the docs and also to any "Basics" section as I think this might be a forefront operation that I neither could find in the docs nor any other online resource.

**Comment by emstoudenmire** [comment]
Hi just wanted to say thanks for your suggestion that we improve the ITensor docs to discuss this point. It's a good idea so we have done so here:
https://itensor.github.io/ITensors.jl/dev/examples/ITensor.html#Tracing-an-ITensor-1

That code example will appear in the main docs as soon as we tag the next version of ITensor.
