### ISSUE TITLE
unexpected error about exp function

### ISSUE THREAD

**Issue by phymann** [ITensor/ITensors.jl#675]
Dear Itensor developers,

In the [documentation](https://itensor.github.io/ITensors.jl/stable/ITensorType.html#Math-operations-1), the function `Base.exp` is introduced which basically treats a tensor `A` as a matrix $A_{lr}$, by specifying some indices as the L index, and the rest as the R index (I'm fully aware of the three constraints given there, like L/R indices should have equal length and their sum should equal to `length(inds(A))`.

However, when testing this function, I found some unexpected results:
1. Why this examples returns error?
```
julia> i = Index(2); j = Index(2); A = ITensor(i,j); exp(A, Linds = i, Rinds = j)
ERROR: Number of left and right indices must add up to total number of indices
```
2. While this example works.
```
julia> i = Index(2); A = ITensor(i,i'); exp(A, Linds = i, Rinds = i')
ITensor ord=2 (dim=2|id=740) (dim=2|id=740)'
NDTensors.Dense{Float64, Vector{Float64}}
```
3. This example again returns error.
```
julia> i = Index(2); A = ITensor(i',i''); exp(A, Linds = i', Rinds = i'')
ERROR: Number of left and right indices must add up to total number of indices
```

Best,
Junsen

**Comment by mtfishman** [comment]
Hi,

`Linds` and `Rinds` are just regular arguments input into the function, not keyword arguments, so they should be input like:
```julia
julia> i = Index(2); j = Index(2); A = randomITensor(i,j); exp(A, (i,), (j,))
ITensor ord=2 (dim=2|id=982) (dim=2|id=139)
ITensors.NDTensors.Dense{Float64, Vector{Float64}}
```
Also note that for now it doesn't accept individual indices as inputs for the left and right indices, only collections, so here I turn them into tuples. You can also do:
```julia
julia> i = Index(2); j = Index(2); A = randomITensor(i,j); exp(A, [i], [j])
ITensor ord=2 (dim=2|id=866) (dim=2|id=107)
ITensors.NDTensors.Dense{Float64, Vector{Float64}}
```

-Matt

**Comment by mtfishman** [comment]
In general for documentation, the convention is that keyword arguments follow a semicolon, so since `Linds` and `Rinds` come before the semicolon:
```julia
exp(A::ITensor, Linds=Rinds', Rinds=inds(A,plev=0); ishermitian = false)
```
it indicates they are just normal arguments, not keyword arguments.

**Comment by phymann** [comment]
> In general for documentation, the convention is that keyword arguments follow a semicolon, so since `Linds` and `Rinds` come before the semicolon:
> 
> ```julia
> exp(A::ITensor, Linds=Rinds', Rinds=inds(A,plev=0); ishermitian = false)
> ```
> 
> it indicates they are just normal arguments, not keyword arguments.

Thank you very much for the explanation and this additional tip, Matt. Now I can go through the documentation with a clearer understanding :)
