### ISSUE TITLE
Implement writing of types to disk

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#68]
A key question is what format to use. Probably HDF5 using a simple subset of its features is best. I just tried installing HDF5.jl on Mac and it was quite fast and easy–in the past I gather the installation would take a long time and fail often so it seems they've improved it!

Another alternative format is BSON. Finally we could offer a straight binary format and/or Julia serialize, which would not require installing any libraries.  Perhaps we can make a simple wrapper that allows us to offer whichever one a user prefers without us needing to code each one for every type in ITensors.jl.

**Comment by kshyatt** [comment]
HDF5.jl is nice because the output files can be used from C++ ITensor. JLD2.jl is another option.

**Comment by emstoudenmire** [comment]
Yes and Olivier is working on a HDF5 library for C++ (the existing one is quite bad!) so that's another reason to want to go HDF5. I could see a good use of this feature where people with existing code in C++ do their calculations there but then switch to Julia to do measurements, say.
