### ISSUE TITLE
An error in doc

### ISSUE THREAD

**Issue by phymann** [ITensor/ITensors.jl#683]
Dear ITensor developers,

Thank you for this big update. Wish one day I can also make contributions to this wonderful project!

Here, I just want to remind you that in [documentation](https://itensor.github.io/ITensors.jl/stable/MPSandMPO.html#ITensors.correlation_matrix-Tuple%7BMPS,%20AbstractString,%20AbstractString%7D) there is an error:
In the example of using `correlation_matrix`, the abandoned `correlator` is used instead of the `correlation_matrix`.

Best,
Junsen

**Comment by emstoudenmire** [comment]
Thank you! We will fix.
