### ISSUE TITLE
Put ITensors. in front of site_type codes?

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#703]
Users are sometimes looking at the provided SiteTypes within ITensor, such as “S=1/2”, “Fermion”, “Electron”, which is a reasonable thing to do and something we should encourage. However, the functions there are not prepended with ITensors. nor is there an import statement at the top (for obvious reasons since it’s inside the ITensor module). 

Making this code more like what users would write themselves could be valuable both for teaching/documentation reasons and to test further that the system works. I can see two ways to do this:
1. actually move these code files outside the ITensors module, and then put an import statement at the top of each
2. prepend the functions in these files with ITensors.

The advantage of #2 is that not only could the entire file be used as a template, but users could even copy and paste individual functions to, say, just add one operator they need for “S=1/2” for example.

**Comment by emstoudenmire** [comment]
This issue was inspired by the following exchange on the forum:
http://itensor.org/support/3237/strange-inconsistency-in-free-fermion-benchmark

**Comment by mtfishman** [comment]
I would vote for both putting them in a module and overloading them with `ITensors.*`.
