### ISSUE TITLE
Generalizations of `OpSum` interface

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#722]
Forum user lello suggested the following, which could be very useful: in input to OpSum, instead of only specifying operators by strings, one should be able to put a Julia matrix instead. 

For example:

```julia
M1::Matrix
M2::Matrix
os = OpSum()
os += M1,i,M2,j
```

For more discussion and examples: http://itensor.org/support/3322/using-kwargs-with-itensors-op-and-autompo-in-julia

**Comment by mtfishman** [comment]
Another generalization is allowing a function as the first input of the term, representing a function that will act on the operator after it is formed:
```julia
os = OpSum()
os += exp, "Z", 1
```

Additionally, I had an idea for something a bit more out there. Consider the following:
```julia
X = OpName("X")
Y = OpName("Y")
Z = OpName("Z")

os = Z(1) * Z(2) + X(1) + X(2)
```
The idea would be that `Z(1)` could create the the term `("Z", 1)`, then `Z(1) * Z(2)` could make the term `("Z", 1, "Z", 2)`.

In this case, we can also allow more general lazy operations, so we could have something like:
```julia
os = (1/2)Z(1) * Z(2) + exp(-im * t *X(1)) + X(2)
```
