### ISSUE TITLE
indexing NDTensor does not work as expected

### ISSUE THREAD

**Issue by chreggi** [ITensor/ITensors.jl#774]
Indexing an NDTensor of more than one Index does not work properly. If one index is fixed to a certain value n>1, the returned tensor has dimension n instead of 1. This only happens if another index is indexed over a range.

```julia
using ITensors
using ITensors.NDTensors

i = Index(2)
j = Index(2)

T = randomITensor(i, j)
dims(tensor(T)[2, 1:end])  # -> (2, 2) instead of (1, 2)
```

I would expect that fixing `i=>2` would return a `(1, space(j))`-dimensional tensor. This new behaviour occurred after we updated from `ITensors v0.1.34` to `v0.1.41`.

**Version information**
Julia: 
```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, icelake-client)
```
ITensors:
` ITensors v0.1.41`

**Comment by mtfishman** [comment]
Oh boy, that's a bad bug, thanks. I can confirm it is also an issue on the `main` branch (ITensors v0.2.10).
