### ISSUE TITLE
[ENHANCEMENT] `expect` interface

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#800]
I think a better design for the `expect` function interface would be the following:

1. A version `expect(psi::MPS, ops::Vector{<:AbstractString})` that return `Vector{Vector{Float64}}`.
2. A version `expect(psi::MPS, op::AbstractString)` that returns `Vector{Float64}`, which is a wrapper around version 1.

I also think we should always return a `Vector` of results even if there is only a single site in the `site_range`.

The reasoning is twofold:

1. Type stability. In this case, it is not an issue of the performance cost of type instability, but I think it is a design goal we should strive for in general unless there is a very compelling reason (like the site type system, or the `ITensor` type design). Type stability is a good design goal since it helps with predictability of the code: the Julia compiler can predict what types are output based on what types are input, but so can users, which I think in general helps make the code more self-documenting and less surprising.
2. Related to the "surprise" factor in comment 1., it would help with writing generic code. For example, say that someone is writing a generic code that wraps `expect` and does some analysis (say averages all of the expectation values). In the current design, the implementation would have to look something like this:
```julia
function expect_mean(psi::MPS, ops::AbstractString...; kwargs...)
  os = expect(psi, ops...; kwargs...)
  if length(ops) == 1
    return os
  end
  return mean(os)
end
```
while in the current interface proposal, it could look like this:
```julia
function expect_mean(psi::MPS, ops::Vector{<:AbstractString}; kwargs...)
  return mean(expect(psi, ops; kwargs...))
end
```
Similar branching logic might have to be done to handle the special case of `length(site_range) == 1` as well (not in this case, since `mean` is generic for `Vector` or `Number`, but for other situations where that isn't the case).

Also see the discussion in https://github.com/ITensor/ITensor/pull/402.

**Comment by emstoudenmire** [comment]
Agreed with these changes, especially about always returning a vector even in the 1-site case for the reasons you said.

For some reason I had made the multi-operator case return a tuple of vectors rather than a vector of vectors. Maybe I was overly worried about saving a few allocations? Please let me know if you can think of a good reason to keep the tuple of vectors structure, otherwise I have no problem with it switching to vector of vectors.

**Comment by mtfishman** [comment]
My apologies, I think I jumped the gun a bit with my proposal and didn't look carefully enough at the current design. Here is the current behavior:
```julia
julia> using ITensors

julia> s = siteinds("S=1/2", 2);

julia> ψ = randomMPS(s);

julia> expect(ψ, "Sz")
2-element Vector{Float64}:
 -0.22709818200554424
  0.46010438579925306

julia> expect(ψ, "Sz", "Sx")
([-0.22709818200554424, 0.46010438579925306], [-0.44545080057148473, -0.1957139600751363])
```
which I think is a good design. This can in fact be made type stable (the one-operator case can be special-cased by the compiler). I also think it is not too surprising from a user perspective (a Tuple is a natural thing to output to match Vararg inputs).

However, I would propose changing this behavior:
```julia
julia> expect(ψ, "Sz"; site_range=1:1)
-0.22709818200554424

julia> expect(ψ, "Sz", "Sx"; site_range=1:1)
2-element Vector{Float64}:
 -0.22709818200554424
 -0.44545080057148473
```
to return the same types/containers as the examples above.

So I think the proposal would be to add support for one or both of the following:
```julia
julia> expect(ψ, ("Sz", "Sx"))
([-0.22709818200554424, 0.46010438579925306], [-0.44545080057148473, -0.1957139600751363])

julia> expect(ψ, ["Sz", "Sx"])
2-element Vector{Vector{Float64}}:
 [-0.22709818200554424, 0.46010438579925306]
 [-0.44545080057148473, -0.1957139600751363]
```
which follow the rule that the output container matches the container of the input operators. These cases would help when writing generic code, like the `expect_mean` function I showed above could be written as:
```julia
function expect_mean(psi::MPS, ops; kwargs...)
  return mean(expect(psi, ops; kwargs...))
end
```
where `ops` is either a `Vector{String}` or `Tuple{Vararg{String}}`.

We could consider removing the version `expect(ψ, "Sz", "Sx")` in favor of `expect(ψ, ("Sz", "Sx"))` (since the latter version is more amenable to writing generic code), but I'm not sure that is necessary.

**Comment by emstoudenmire** [comment]
Yes, I definitely support changing the current behavior in the case of the site range being 1:1. Even apart from type stability issues, that was a bad design decision of mine just from a generic code / consistency perspective.

I'm not sure I fully understand the importance of propagating the container type for the ops argument though. Is it because in generic code, one can grab that type and use it again in another place? In the `expect_mean` example, wouldn't the `mean` function be able to handle either a tuple or vector input regardless of what type `ops` is? Thanks for explaining a bit more.

**Comment by mtfishman** [comment]
One reason would be type stability. If you took a `Vector{String}` input and output a `Tuple`, the length of the `Tuple` would be undefined at compile time, so would be type unstable.

The other way, where you have a `Tuple{Vararg{String}}` input which outputs a `Vector` of results, I suppose is fine. However, someone may specifically want a `Tuple` output for a variety of reasons (for example, a `Tuple` can be dispatched on based on the length and positional element types), so in this way we implicitly give them a choice for the output type.

One way to see the choice of matching the output type to the input type is the analog to generic Julia functions like `map` or broadcasting, which preserve the input type:
```julia
julia> map(x -> 2x, [1, 2, 3])
3-element Vector{Int64}:
 2
 4
 6

julia> map(x -> 2x, (1, 2, 3))
(2, 4, 6)

julia> 2 .* [1, 2, 3]
3-element Vector{Int64}:
 2
 4
 6

julia> 2 .* (1, 2, 3)
(2, 4, 6)
```
and the single value case:
```julia
julia> map(x -> 2x, 1)
2

julia> 2 .* 1
2
```
We can think of the `expect` function with multiple input operators as semantically equivalent to:
```julia
expect(m::MPS, ops) = map(o -> expect(m, o), ops)
```
though implemented in a more efficient way (in fact, `map` in Julia has special optimized cases for certain function inputs).

A more interesting use case might be supporting other input and output types, like a general `Matrix{String}`/`Array{String}` or a dictionary mapping the operator name to the results, so an input of `Dict{String,String}` and an output `Dict{String,Vector{Float64}}`, for example. That would fit with the Observers.jl dictionary-like interface (https://github.com/GTorlai/Observers.jl).
