### ISSUE TITLE
[ITensors] [BUG] AutoMPO conflicts with the Gnuplot.jl dependency StructC14N.jl

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#814]
**Description of bug**
Describe the bug clearly and concisely.

When using the OpSum AutoMPO backend, an error is received: `ERROR: LoadError: MethodError: convert(::Type{NamedTuple}, ::NamedTuple{(), Tuple{}}) is ambiguous.`

**How to reproduce**
Detail steps to reproduce the behavior.

Reproduce by doing `using Gnuplot` then using OpSum and converting it to an MPO.

**Code demonstrating bug**
If applicable, provide a minimal working example of the bug.

```
using ITensors
using Gnuplot
let
  N = 10
  sites = siteinds("S=1",N)

  ampo = OpSum()
  for j=1:N-1
    ampo += "Sz",j,"Sz",j+1
  end
  H = MPO(ampo,sites)
end
```

**Version information**
 - output from `versioninfo()` surrounded by backticks (``)
`Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, westmere)
Environment:
  JULIA_DIR = /Applications/Julia-1.7.app/Contents/Resources/julia`

 - output from `] status ITensors` surrounded by backticks (``)
 ```
      Status `~/.julia/environments/v1.7/Project.toml`
  [9136182c] ITensors v0.2.12
```

**Comment by emstoudenmire** [comment]
The error message traces back to the package StructC14N.jl  https://github.com/gcalderone/StructC14N.jl
which is a dependency of Gnuplot.jl.

Not sure whether StructC14N.jl needs to define the convert function better or not export it, or whether a similar action is needed within ITensor.

**Comment by mtfishman** [comment]
This is independent of ITensors.jl, for example:
```julia
julia> convert(NamedTuple, (;))
NamedTuple()

julia> using StructC14N

julia> convert(NamedTuple, (;))
ERROR: MethodError: convert(::Type{NamedTuple}, ::NamedTuple{(), Tuple{}}) is ambiguous. Candidates:
  convert(::Type{T}, x::T) where T in Base at essentials.jl:218
  convert(::Type{NamedTuple}, str) in StructC14N at /home/mfishman/.julia/packages/StructC14N/7Prm0/src/StructC14N.jl:16
Possible fix, define
  convert(::Type{NamedTuple}, ::NamedTuple)
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1
```
I raised an issue over at StructC14N.jl: https://github.com/gcalderone/StructC14N.jl/issues/2

**Comment by emstoudenmire** [comment]
Great. Thanks for taking the time to look into this. I'll close it since it's therefore certainly a bug with StructC14N, and no action to be taken with ITensor.
