### ISSUE TITLE
factorization with `eigen` does not respect `tags` keyword

### ISSUE THREAD

**Issue by orialb** [ITensor/ITensors.jl#82]
Hi,
It seems that the issue of bond tags not being conserved when `replaceBond!` is not fully fixed by https://github.com/ITensor/ITensors.jl/pull/81, because the factorization functions using `eigen` don't respect the `tags` keyword. My tests where unfortunately such that only SVD was used. 

I think a small change in `storage_eigen` fixes that (see https://github.com/orialb/ITensors.jl/commit/91515529ee5e5b8ad0ee8fd5742cb2cff6d46311) . 
I wanted to ask if this is how you meant it to be handled, because I saw that in the case of svd factorization the tags replacement is done in the `_factorize...` function and not in the `storage_svd` function.

**Comment by mtfishman** [comment]
Sorry for the late response about this. That looks like the right fix to me.

**Comment by orialb** [comment]
this was fixed during the re-design of the Tensor storage system. Seems to be working properly now.
