### ISSUE TITLE
[ITensors] [ENHANCEMENT] Dictionary/kwargs interface for sweeps in `dmrg`

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#827]
It would be nice to have a more concise interface for the sweeps object so simple DMRG calculations can be run in a single line.

For example:
```julia
dmrg(H, psi, Sweeps("nsweeps" => 10, "cutoff" => [1e-4, 1e-8], "maxdim" => [50, 100]))

# Maybe this defaults to `nsweeps = max(length(cutoff), length(maxdim)) = 2`?
dmrg(H, psi, Sweeps("cutoff" => [1e-4, 1e-8], "maxdim" => [50, 100]))

# Use `1e-8` and `100` for every sweep
dmrg(H, psi, Sweeps("nsweeps" => 10, "cutoff" => 1e-8, "maxdim" => 100))
```
and/or:
```julia
dmrg(H, psi; nsweeps=10, cutoff=[1e-4, 1e-8], maxdim=[50, 100])

# Maybe defaults to 2 sweeps?
dmrg(H, psi; cutoff=[1e-4, 1e-8], maxdim=[50, 100])

dmrg(H, psi; nsweeps=10, cutoff=1e-8, maxdim=100))
```
The kwarg version could simply forward the values to the constructor that implements the first syntax, so it is all just syntactic sugar on top of the current interface.

We could also pick some reasonable defaults like `cutoff=1e-8` so you can just run `dmrg` directly on simple systems (like we do with `MPS + MPS` and `MPO * MPS`). Of course that will quickly fail for any MPOs that are moderately complicated.

The sweeps object would still be helpful for more complicated situations (more sophisticated runs where more parameters like noise are used, and/or where you want to save the Sweeps object to reproduce a DMRG run exactly).

This came up because I wanted to quickly estimate the eigenvalue of a simple Hamiltonian computed with DMRG to compare to gradient optimization, where the `Sweeps` object constructor adds a lot of unnecessary lines of code and mental burden remembering the syntax.

**Comment by emstoudenmire** [comment]
Agree with all or any of the above ideas. In particular I like the more relaxed approach of just passing vectors of numbers through keyword args, with another keyword arg being `nsweeps` or `sweeps` to set the number of sweeps to do in case it should be more than the length of the cutoff of maxdim vectors.

The main thing in my mind to keep the same is that our physics-oriented examples should still emphasize the importance of thinking about a good sweep schedule. We still occasionally see users on the forum not getting good results with the solution turning out to be just doing more sweeeps or using tighter parameters. So just a communication/teaching thing there.

**Comment by mtfishman** [comment]
Oops yes I did not show the `nsweeps` keyword argument there but that would be a necessary one you would need to specify (I don't think it would be a good idea to have a default for that, so then it forces people to think about how many sweeps to use).

Agreed that we will want to emphasize to people in the docs that they need to choose good values for these for their own problems to get good convergence.

**Comment by mtfishman** [comment]
Also something to keep in mind is that when the keyword argument syntax is added, `NamedTuple`s could be used to do the same thing as the Sweeps object (in general you can think of them as a `struct` that you can make on-the-fly and are easily passed as keyword arguments):
```julia
sweeps = (;
  nsweeps=10,
  cutoff=[1e-4, 1e-8],
  maxdim=[50, 100],
)
dmrg(H, psi; sweeps...)
```
This is like the interface I have been using in the `vumps` code in `ITensorInfiniteMPS.jl`.

In general I have tried to go in the direction of using built-in Julia types when possible, since then you don't need to invent new syntax and can automatically get a lot of features that people (hopefully) know how to use already.
