### ISSUE TITLE
[ITensors] [ENHANCEMENT] Add `+` operation in the `op` system

### ISSUE THREAD

**Issue by GTorlai** [ITensor/ITensors.jl#854]
Introduce the addition (over the multiplication currently implemented) for `op`:
```julia
q = siteind("Qudit"; dim = 4)
X = op("a + a†", q)
```
To avoid clashing with operators like "S+", we can check whether there is a space between the `+` and nearby `chars`.

**Comment by mtfishman** [comment]
Closed by #857.
