### ISSUE TITLE
Consider renaming In and Out

### ISSUE THREAD

**Issue by MasonProtter** [ITensor/ITensors.jl#9]
Both IJulia.jl and ITensors.jl export the names `In` and `Out`. This doesn't necessarily need to be fixed but it means that anyone working in a jupyter notebook needs to write `ITenors.In` and `ITensors.Out` instead of `In` or `Out`. 

The easiest solution would be to rename them to `in` and `out`, which would make some sense since they aren't types but fancy integers and usually only types have upper cased names in Julia.

Another option would be `contavariant` and `covariant` but that's pretty verbose.

**Comment by nickrobinson251** [comment]
remember `in` is a Base functions, so that's not really available :)

**Comment by MasonProtter** [comment]
Oof. right.

**Comment by MasonProtter** [comment]
`up` and `dn` / `down`?

**Comment by kshyatt** [comment]
`up` and `dn` are not good names, I think, because `In` and `Out` are supposed to express quantum number conservation, and these two would quickly lead to confusion in any model with a conserved quantum number.

**Comment by emstoudenmire** [comment]
Also tensor diagrams are orientation independent (excepting some “house” conventions used by various groups)

**Comment by emstoudenmire** [comment]
Maybe we should use strings? “In” and “Out” ? Mostly these don’t get used since indices default to having an Out arrow and get flipped by calling dag on them.

**Comment by emstoudenmire** [comment]
Meaning it may be ok to type ITensor.In and ITensor.Out anyhow since they don’t really come up much in typical usage (even in developer code!)

**Comment by MasonProtter** [comment]
Yeah, I think moving to a string interface would be worse than just requiring someone to manually disambiguate between other packages `In` and `Out`.

**Comment by MasonProtter** [comment]
Perhaps if they don't come up much, even in developer code, they should not be exported by default then? That way no names need to be changed and jupyter users don't get pesky warning messages.

**Comment by mtfishman** [comment]
It seems reasonable to just not export them.

**Comment by emstoudenmire** [comment]
Yes, I think it's the best solution for now, and we may find we essentially never need to export them. (Or when needed one can explicitly import them.)
