### ISSUE TITLE
[ITensors] [BUG] Float32 with randomMPS and svd of randomITensor(Float32, indices)

### ISSUE THREAD

**Issue by ArtemStrashko** [ITensor/ITensors.jl#928]
**Description of bug**

Cannot get randomMPS with Float32. Cannot svd a randomITensor(Float32, indices).  

**Minimal code demonstrating the bug or unexpected behavior**

<details><summary>Minimal runnable code</summary><p>

```julia
using ITensors
randomMPS(Float64, [Index(2) for _ in 1:10])
randomMPS(ComplexF64, [Index(2) for _ in 1:10])
```
works well, but 
```julia
randomMPS(Float32, [Index(2) for _ in 1:10]) 
```
returns an error: MethodError: no method matching (::ITensors.var"#_rmatrix#847")(::Type{Float32}, ::Int64, ::Int64).

Also, while one could get a randomITensor with Float32 precision 
```julia
i = Index(2)
A = randomITensor(Float32, i', i);
```
an svd then does not work
```julia
svd(A, i'; maxdim=2)
```
and throws an error: MethodError: no method matching truncate!(::Vector{Float32}; mindim=1, maxdim=2, cutoff=0.0, use_absolute_cutoff=false, use_relative_cutoff=true)
</p></details>

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731* (2021-11-30 12:12 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD EPYC 7742 64-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver2)
Environment:
  JULIA_NUM_THREADS = 128

```
 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
Status `~/.julia/environments/v1.7/Project.toml`
  [9136182c] ITensors v0.2.16
```

**Comment by mtfishman** [comment]
Thanks @ArtemStrashko, I'm fixing these in #926.
