### ISSUE TITLE
Possible bug in `delta`

### ISSUE THREAD

**Issue by alvarorga** [ITensor/ITensors.jl#93]
Hi, 
let's suppose I have an `ITensor` with indices `(i, i', m)` with dimension, e.g. `(3, 3, 2)`. If I contract that `ITensor` with `delta(i, i')`, the contraction returns the sum of the elements `[1, 1, 1]` + `[2, 2, 1]` of the `ITensor` and not the sum of the elements `[1, 1, 1]`+`[2, 2, 1]`+`[3, 3, 1]`. 

A MWE showing this 
```julia
using LinearAlgebra, Test, ITensors

idim = 3
mdim = 2 # Test will fail whenever mdim < idim
    
i = Index(idim, "i")
m = Index(mdim, "m")
    
A = randomITensor(i, i', m)
    
# Using delta.
O = A*δ(i, i')
    
# Manual trace.
P = map(i -> tr(Array(A)[:, :, i]), 1:mdim)

@test Array(O) ≈ P
```

Is that the expected behavior of `delta`?

**Comment by mtfishman** [comment]
Is this fixed on master? That test passes for me with mdim < idim. Either way it would be a good test to add.

**Comment by mtfishman** [comment]
Sorry, I am seeing this bug in master (I was accidentally using a different version of ITensors.jl). I will take a look into this, thanks!
