### ISSUE TITLE
[ITensors] [BUG] autodifferentiation of scalar multiplied by `tr` of MPOs

### ISSUE THREAD

**Issue by hjkqubit** [ITensor/ITensors.jl#936]
**Description of bug**

Taking the derivative of `a` multiplied by `tr(A)`, where `A` is an MPO,  with respect to `A` produces erroneous results if `a` isn't 1.

**Minimal code demonstrating the bug or unexpected behavior**

<details><summary>Minimal runnable code</summary><p>

```julia
using ITensors
using Zygote
using Random

Random.seed!(1234)

L = 2
sites = siteinds("S=1/2",L)
x = randomMPS(sites)
y = randomMPS(sites)
A₀ = outer(x',y)

function fun1(A::MPO)
    return tr(A)
end

function fun2(A::MPO)
    return 2*tr(A)
end

function fun3(A::MPO)
    return -tr(A)
end

function matricize(M::MPO)
    sites = siteinds(M; plev=0)
    C = combiner(sites)
    return matrix(prod(M) * C' * C)
end

∂fun1(A) = fun1'(A)
∂fun1x = ∂fun1(A₀)

@show matricize(∂fun1x)

∂fun2(A) = fun2'(A)
∂fun2x = ∂fun2(A₀)

@show matricize(∂fun2x)

∂fun3(A) = fun3'(A)
∂fun3x = ∂fun3(A₀)

@show matricize(∂fun3x)
```
</p></details>

**Expected output or behavior**

We would expect to see I, 2I, and -I, where I is the 4x4 identity matrix, for the respective @show functions, since d(tr(A))/dA is simply I and so d(2*tr(A))/dA should return 2I and d(-tr(A))/dA should return -I.

**Actual output or behavior**

Instead, we find that the outputs are I, 4I, and I. This suggests that the scalars are multiplied with each other in the final output.

<details><summary>Output of minimal runnable code</summary><p>

```julia
matricize(∂fun1x) = [1.0000000000000004 0.0 0.0 0.0; 0.0 1.0000000000000007 0.0 0.0; 0.0 0.0 1.0000000000000002 0.0; 0.0 0.0 0.0 1.0000000000000004]
matricize(∂fun2x) = [4.000000000000002 0.0 0.0 0.0; 0.0 4.000000000000003 0.0 0.0; 0.0 0.0 4.000000000000001 0.0; 0.0 0.0 0.0 4.000000000000002]
matricize(∂fun3x) = [1.0000000000000004 0.0 0.0 0.0; 0.0 1.0000000000000007 0.0 0.0; 0.0 0.0 1.0000000000000002 0.0; 0.0 0.0 0.0 1.0000000000000004]
```
</p></details>

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 9 4900HS with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver2)
```
 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
      Status `C:\Users\hjkqu\.julia\environments\v1.7\Project.toml`
  [9136182c] ITensors v0.3.16
```

**Comment by mtfishman** [comment]
Very strange bug...

**Comment by mtfishman** [comment]
I found the source of the bug, you can see the derivative is being multiplied twice in the pullback for `tr`:
https://github.com/ITensor/ITensors.jl/blob/d9333748f5d891a555fc8507a71fba189dc610b8/src/ITensorChainRules/mps/mpo.jl#L57-L65

**Comment by mtfishman** [comment]
Fixed by https://github.com/ITensor/ITensors.jl/commit/b66d1b7c1f0b67332d07d7b539c6916dbe6d673c.
