### ISSUE TITLE
[ITensors] [BUG] exp(loginner()) not equivalent to inner()

### ISSUE THREAD

**Issue by amilsted** [ITensor/ITensors.jl#944]
**Description of bug**

Computing an expectation value using loginner() does not provide sign or phase information.

**Expected output or behavior**

When computing `loginner(mps', H, mps)` for some MPS `mps` and some Hamiltonian `H`, I expect the result to be approximately equal to `inner(mps', H, mps)`. The documentation suggests this is the intended behavior and this would be useful for operators of large norm that are not positive or even Hermitian.

**Actual output or behavior**

Instead, e.g. if `mps` is the groundstate of `H` with negative energy, `loginner(mps', H, mps)` returns a value equal to `abs(inner(mps', H, mps))`.

**Comment by amilsted** [comment]
Thanks Matt. Out of interest, what kind of floating-point errors is the warning "The inner product (or norm²) you are computing is very large..." supposed to be protecting me against? Have you found a reason to doubt the result of `inner()` itself in these cases?

**Comment by mtfishman** [comment]
Now that you ask, it seems like it doesn't help much unless you have cases that actually overflow. Take this example:
```julia
using ITensors

function main(; n, c)
  s = siteinds("S=1/2", n);
  ψ = c .* randomMPS(s; linkdims=4)
  return inner(ψ, ψ), log(inner(ψ, ψ)), loginner(ψ, ψ)
end
```
```julia
julia> main(; n=100, c=20)
┌ Warning: The inner product (or norm²) you are computing is very large: 1.60693804425899e260, which is greater than 4.503599627370496e15 and may lead to floating point errors when used. You should consider using `lognorm` or `loginner` instead, which will help avoid floating point errors. For example if you are trying to normalize your MPS/MPO `A`, the normalized MPS/MPO `B` would be given by `B = A ./ z` where `z = exp(lognorm(A) / length(A))`.
└ @ ITensors ~/.julia/dev/ITensors/src/mps/abstractmps.jl:1099
┌ Warning: The inner product (or norm²) you are computing is very large: 1.60693804425899e260, which is greater than 4.503599627370496e15 and may lead to floating point errors when used. You should consider using `lognorm` or `loginner` instead, which will help avoid floating point errors. For example if you are trying to normalize your MPS/MPO `A`, the normalized MPS/MPO `B` would be given by `B = A ./ z` where `z = exp(lognorm(A) / length(A))`.
└ @ ITensors ~/.julia/dev/ITensors/src/mps/abstractmps.jl:1099
(1.60693804425899e260, 599.1464547107983, 599.146454710798)

julia> main(; n=200, c=20)
┌ Warning: The inner product (or norm²) you are computing is very large: NaN, which is greater than 4.503599627370496e15 and may lead to floating point errors when used. You should consider using `lognorm` or `loginner` instead, which will help avoid floating point errors. For example if you are trying to normalize your MPS/MPO `A`, the normalized MPS/MPO `B` would be given by `B = A ./ z` where `z = exp(lognorm(A) / length(A))`.
└ @ ITensors ~/.julia/dev/ITensors/src/mps/abstractmps.jl:1099
┌ Warning: The inner product (or norm²) you are computing is very large: NaN, which is greater than 4.503599627370496e15 and may lead to floating point errors when used. You should consider using `lognorm` or `loginner` instead, which will help avoid floating point errors. For example if you are trying to normalize your MPS/MPO `A`, the normalized MPS/MPO `B` would be given by `B = A ./ z` where `z = exp(lognorm(A) / length(A))`.
└ @ ITensors ~/.julia/dev/ITensors/src/mps/abstractmps.jl:1099
(NaN, NaN, 1198.2929094215954)
```
So perhaps it isn't worth warning about it unless you actually get a `NaN` result, though it may still be good to let people know they are getting very large norms...

I guess depending on what you are calculating, you may lose precision when dealing with inner products that are so large. I don't have a particular example in mind but I remember seeing these overflows happening in actual use cases which led to loss of precision in something I was calculating.

An alternative design I considered for handling cases of very small or large inner products/norms was to store an "inner product per site", for example a Vector containing the norms of intermediate tensors involved in the inner product.

**Comment by amilsted** [comment]
@mtfishman Thanks for fixing this! Should I open another issue about the inner() warning? It's easy to trigger in "legitimate" cases too, such as when computing expectation values of a Hamiltonian that just happens to have large energy scale.

**Comment by mtfishman** [comment]
What do you suggest the change should be? I have found that the current warning catches cases where we are clearly doing something wrong, do you think it is best to raise the limit or only check for the case of actual overflow, i.e. results of `NaN`?

**Comment by mtfishman** [comment]
Yeah I think I'll just change it to only warn for NaNs or Infs, since you have some use cases where the warning is superfluous.
